/*Use to create a table of first names and last names*/
CREATE OR REPLACE TABLE test.meta_namepart
(
    name_id	INT64,
    name_part	STRING,
    name_part_type	STRING
) 
PARTITION BY RANGE_BUCKET(name_id, GENERATE_ARRAY(1, 1000000000, 100000))
CLUSTER BY (name_id)
;

/*this enters letters of the alphabet, used later for middle initials*/
INSERT INTO test.meta_namepart
SELECT
    (SELECT IFNULL(MAX(name_id), 0) FROM test.meta_namepart) + ROW_NUMBER() OVER(),
    np.name_part,
    'letter' AS name_part_type
FROM
    (
        SELECT 'A' AS name_part 
        UNION ALL
        SELECT 'B' UNION ALL
        SELECT 'C' UNION ALL
        SELECT 'D' UNION ALL
        SELECT 'E' UNION ALL
        SELECT 'F' UNION ALL
        SELECT 'G' UNION ALL
        SELECT 'H' UNION ALL
        SELECT 'I' UNION ALL
        SELECT 'J' UNION ALL
        SELECT 'K' UNION ALL
        SELECT 'L' UNION ALL
        SELECT 'M' UNION ALL
        SELECT 'N' UNION ALL
        SELECT 'O' UNION ALL
        SELECT 'P' UNION ALL
        SELECT 'Q' UNION ALL
        SELECT 'R' UNION ALL
        SELECT 'S' UNION ALL
        SELECT 'T' UNION ALL
        SELECT 'U' UNION ALL
        SELECT 'V' UNION ALL
        SELECT 'W' UNION ALL
        SELECT 'X' UNION ALL
        SELECT 'Y' UNION ALL
        SELECT 'Z'
    ) np
;


/*this creates a list of gender neutral first names*/
/*combined from the following websites:
https://wehavekids.com/baby-names/gender-neutral-names
https://en.wikipedia.org/wiki/Unisex_name
https://www.babycentre.co.uk/a1026121/unisex-baby-names
*/
INSERT INTO test.meta_namepart
SELECT
    (SELECT IFNULL(MAX(name_id), 0) FROM test.meta_namepart) + ROW_NUMBER() OVER(),
    np.*,
    'first name' AS name_part_type
FROM
    (
        SELECT 'Addison' UNION ALL
        SELECT 'Adlai' UNION ALL
        SELECT 'Adrian' UNION ALL
        SELECT 'Aiden' UNION ALL
        SELECT 'Ainsley' UNION ALL
        SELECT 'Alby' UNION ALL
        SELECT 'Alex' UNION ALL
        SELECT 'Alexis' UNION ALL
        SELECT 'Ali' UNION ALL
        SELECT 'Amari' UNION ALL
        SELECT 'Amen' UNION ALL
        SELECT 'Amory' UNION ALL
        SELECT 'Andie' UNION ALL
        SELECT 'Andy' UNION ALL
        SELECT 'Angel' UNION ALL
        SELECT 'Archer' UNION ALL
        SELECT 'Arden' UNION ALL
        SELECT 'Ari' UNION ALL
        SELECT 'Ariel' UNION ALL
        SELECT 'Armani' UNION ALL
        SELECT 'Arrow' UNION ALL
        SELECT 'Arya' UNION ALL
        SELECT 'Ash' UNION ALL
        SELECT 'Ashley' UNION ALL
        SELECT 'Ashton' UNION ALL
        SELECT 'Aspen' UNION ALL
        SELECT 'Aubrey' UNION ALL
        SELECT 'Auden' UNION ALL
        SELECT 'August' UNION ALL
        SELECT 'Austin' UNION ALL
        SELECT 'Austen' UNION ALL
        SELECT 'Avery' UNION ALL
        SELECT 'Avis' UNION ALL
        SELECT 'Azariah' UNION ALL
        SELECT 'Bailey' UNION ALL
        SELECT 'Baker' UNION ALL
        SELECT 'Bay' UNION ALL
        SELECT 'Bellamy' UNION ALL
        SELECT 'Bergen' UNION ALL
        SELECT 'Bevan' UNION ALL
        SELECT 'Billy' UNION ALL
        SELECT 'Billie' UNION ALL
        SELECT 'Blaine' UNION ALL
        SELECT 'Blair' UNION ALL
        SELECT 'Blake' UNION ALL
        SELECT 'Blue' UNION ALL
        SELECT 'Bobby' UNION ALL
        SELECT 'Bowie' UNION ALL
        SELECT 'Brady' UNION ALL
        SELECT 'Brennan' UNION ALL
        SELECT 'Brent' UNION ALL
        SELECT 'Breslin' UNION ALL
        SELECT 'Brett' UNION ALL
        SELECT 'Briar' UNION ALL
        SELECT 'Brighton' UNION ALL
        SELECT 'Bronwyn' UNION ALL
        SELECT 'Brook' UNION ALL
        SELECT 'Brooke' UNION ALL
        SELECT 'Brooklyn' UNION ALL
        SELECT 'Caelan' UNION ALL
        SELECT 'Cameron' UNION ALL
        SELECT 'Campbell' UNION ALL
        SELECT 'Carmel' UNION ALL
        SELECT 'Carmen' UNION ALL
        SELECT 'Carroll' UNION ALL
        SELECT 'Carson' UNION ALL
        SELECT 'Carter' UNION ALL
        SELECT 'Karter' UNION ALL
        SELECT 'Casey' UNION ALL
        SELECT 'Cassidy' UNION ALL
        SELECT 'Celyn' UNION ALL
        SELECT 'Chandler' UNION ALL
        SELECT 'Channing' UNION ALL
        SELECT 'Charleston' UNION ALL
        SELECT 'Charlie' UNION ALL
        SELECT 'Charley' UNION ALL
        SELECT 'Chris' UNION ALL
        SELECT 'Kris' UNION ALL
        SELECT 'Christian' UNION ALL
        SELECT 'Clancy' UNION ALL
        SELECT 'Clarke' UNION ALL
        SELECT 'Clay' UNION ALL
        SELECT 'Clayton' UNION ALL
        SELECT 'Cleo' UNION ALL
        SELECT 'Cody' UNION ALL
        SELECT 'Corey' UNION ALL
        SELECT 'Cypress' UNION ALL
        SELECT 'Dakota' UNION ALL
        SELECT 'Dakotah' UNION ALL
        SELECT 'Dale' UNION ALL
        SELECT 'Dallas' UNION ALL
        SELECT 'Dana' UNION ALL
        SELECT 'Dane' UNION ALL
        SELECT 'Darby' UNION ALL
        SELECT 'Darrel' UNION ALL
        SELECT 'Darryl' UNION ALL
        SELECT 'Daryl' UNION ALL
        SELECT 'Dawson' UNION ALL
        SELECT 'Delta' UNION ALL
        SELECT 'Denver' UNION ALL
        SELECT 'Devin' UNION ALL
        SELECT 'Devon' UNION ALL
        SELECT 'Dominique' UNION ALL
        SELECT 'Dorian' UNION ALL
        SELECT 'Drew' UNION ALL
        SELECT 'Dylan' UNION ALL
        SELECT 'Easton' UNION ALL
        SELECT 'Eastyn' UNION ALL
        SELECT 'Eddie' UNION ALL
        SELECT 'Eden' UNION ALL
        SELECT 'Egypt' UNION ALL
        SELECT 'Eli' UNION ALL
        SELECT 'Ellery' UNION ALL
        SELECT 'Elliot' UNION ALL
        SELECT 'Elliott' UNION ALL
        SELECT 'Ellis' UNION ALL
        SELECT 'Ellison' UNION ALL
        SELECT 'Emerson' UNION ALL
        SELECT 'Emery' UNION ALL
        SELECT 'Emory' UNION ALL
        SELECT 'Erin' UNION ALL
        SELECT 'Ever' UNION ALL
        SELECT 'Everest' UNION ALL
        SELECT 'Fabian' UNION ALL
        SELECT 'Finley' UNION ALL
        SELECT 'Finn' UNION ALL
        SELECT 'Florian' UNION ALL
        SELECT 'Flynn' UNION ALL
        SELECT 'Francis' UNION ALL
        SELECT 'Frances' UNION ALL
        SELECT 'Frankie' UNION ALL
        SELECT 'Gabriel' UNION ALL
        SELECT 'Gene' UNION ALL
        SELECT 'Jean' UNION ALL
        SELECT 'Gentry' UNION ALL
        SELECT 'Gillian' UNION ALL
        SELECT 'Jillian' UNION ALL
        SELECT 'Glen' UNION ALL
        SELECT 'Glenn' UNION ALL
        SELECT 'Gray' UNION ALL
        SELECT 'Grey' UNION ALL
        SELECT 'Greer' UNION ALL
        SELECT 'Hadley' UNION ALL
        SELECT 'Halo' UNION ALL
        SELECT 'Hampton' UNION ALL
        SELECT 'Harley' UNION ALL
        SELECT 'Harlow' UNION ALL
        SELECT 'Harper' UNION ALL
        SELECT 'Haskell' UNION ALL
        SELECT 'Haven' UNION ALL
        SELECT 'Hayden' UNION ALL
        SELECT 'Hero' UNION ALL
        SELECT 'Holland' UNION ALL
        SELECT 'Hollis' UNION ALL
        SELECT 'Honor' UNION ALL
        SELECT 'Hudson' UNION ALL
        SELECT 'Hunter' UNION ALL
        SELECT 'Indiana' UNION ALL
        SELECT 'Indigo' UNION ALL
        SELECT 'Jackie' UNION ALL
        SELECT 'Jaqui' UNION ALL
        SELECT 'Jade' UNION ALL
        SELECT 'Jaden' UNION ALL
        SELECT 'Jaidyn' UNION ALL
        SELECT 'Jayden' UNION ALL
        SELECT 'Jael' UNION ALL
        SELECT 'James' UNION ALL
        SELECT 'Jayme' UNION ALL
        SELECT 'Jamie' UNION ALL
        SELECT 'Jan' UNION ALL
        SELECT 'Jaziah' UNION ALL
        SELECT 'Jesse' UNION ALL
        SELECT 'Jessie' UNION ALL
        SELECT 'Jody' UNION ALL
        SELECT 'Joe' UNION ALL
        SELECT 'Jordan' UNION ALL
        SELECT 'Journey' UNION ALL
        SELECT 'Jules' UNION ALL
        SELECT 'Julian' UNION ALL
        SELECT 'Justice' UNION ALL
        SELECT 'Kaden' UNION ALL
        SELECT 'Kadin' UNION ALL
        SELECT 'Kai' UNION ALL
        SELECT 'Kamryn' UNION ALL
        SELECT 'Camryn' UNION ALL
        SELECT 'Keegan' UNION ALL
        SELECT 'Keelan' UNION ALL
        SELECT 'Keely' UNION ALL
        SELECT 'Kei' UNION ALL
        SELECT 'Keith' UNION ALL
        SELECT 'Keath' UNION ALL
        SELECT 'Kelly' UNION ALL
        SELECT 'Kelsey' UNION ALL
        SELECT 'Kendall' UNION ALL
        SELECT 'Kennedy' UNION ALL
        SELECT 'Kennedi' UNION ALL
        SELECT 'Kensley' UNION ALL
        SELECT 'Kerry' UNION ALL
        SELECT 'Kevin' UNION ALL
        SELECT 'Kieran' UNION ALL
        SELECT 'Kiley' UNION ALL
        SELECT 'Kim' UNION ALL
        SELECT 'Kym' UNION ALL
        SELECT 'Kingsley' UNION ALL
        SELECT 'Kylar' UNION ALL
        SELECT 'Kyle' UNION ALL
        SELECT 'Kylin' UNION ALL
        SELECT 'Kyrie' UNION ALL
        SELECT 'Lake' UNION ALL
        SELECT 'Landry' UNION ALL
        SELECT 'Lane' UNION ALL
        SELECT 'Lee' UNION ALL
        SELECT 'Leigh' UNION ALL
        SELECT 'Lennon' UNION ALL
        SELECT 'Lennox' UNION ALL
        SELECT 'Leslie' UNION ALL
        SELECT 'Lesley' UNION ALL
        SELECT 'Lincoln' UNION ALL
        SELECT 'Linden' UNION ALL
        SELECT 'Lindsay' UNION ALL
        SELECT 'Logan' UNION ALL
        SELECT 'London' UNION ALL
        SELECT 'Lonnie' UNION ALL
        SELECT 'Loren' UNION ALL
        SELECT 'Lou' UNION ALL
        SELECT 'Lucy-Ann' UNION ALL
        SELECT 'Lucian' UNION ALL
        SELECT 'Lumi' UNION ALL
        SELECT 'Lyric' UNION ALL
        SELECT 'Macey' UNION ALL
        SELECT 'Macy' UNION ALL
        SELECT 'Mackenzie' UNION ALL
        SELECT 'Madison' UNION ALL
        SELECT 'Marley' UNION ALL
        SELECT 'Marlo' UNION ALL
        SELECT 'Marlow' UNION ALL
        SELECT 'Mason' UNION ALL
        SELECT 'Max' UNION ALL
        SELECT 'Maxwell' UNION ALL
        SELECT 'Memphis' UNION ALL
        SELECT 'Merit' UNION ALL
        SELECT 'Merritt' UNION ALL
        SELECT 'Micah' UNION ALL
        SELECT 'Michael' UNION ALL
        SELECT 'Micky' UNION ALL
        SELECT 'Milan' UNION ALL
        SELECT 'Miller' UNION ALL
        SELECT 'Monroe' UNION ALL
        SELECT 'Montana' UNION ALL
        SELECT 'Morgan' UNION ALL
        SELECT 'Moriah' UNION ALL
        SELECT 'Murphy' UNION ALL
        SELECT 'Navy' UNION ALL
        SELECT 'Nevada' UNION ALL
        SELECT 'Nicky' UNION ALL
        SELECT 'Nico' UNION ALL
        SELECT 'Nikita' UNION ALL
        SELECT 'Noel' UNION ALL
        SELECT 'Noelle' UNION ALL
        SELECT 'Oakley' UNION ALL
        SELECT 'Ocean' UNION ALL
        SELECT 'Ode' UNION ALL
        SELECT 'Ore' UNION ALL
        SELECT 'Oswin' UNION ALL
        SELECT 'Owen' UNION ALL
        SELECT 'Paris' UNION ALL
        SELECT 'Parker' UNION ALL
        SELECT 'Pat' UNION ALL
        SELECT 'Payson' UNION ALL
        SELECT 'Payton' UNION ALL
        SELECT 'Peyton' UNION ALL
        SELECT 'Peace' UNION ALL
        SELECT 'Perry' UNION ALL
        SELECT 'Perrie' UNION ALL
        SELECT 'Phoenix' UNION ALL
        SELECT 'Piper' UNION ALL
        SELECT 'Poet' UNION ALL
        SELECT 'Quincy' UNION ALL
        SELECT 'Quinn' UNION ALL
        SELECT 'Raleigh' UNION ALL
        SELECT 'Ramsey' UNION ALL
        SELECT 'Raphael' UNION ALL
        SELECT 'Ray' UNION ALL
        SELECT 'Rayne' UNION ALL
        SELECT 'Rain' UNION ALL
        SELECT 'Reagan' UNION ALL
        SELECT 'Rebel' UNION ALL
        SELECT 'Reed' UNION ALL
        SELECT 'Reese' UNION ALL
        SELECT 'Regan' UNION ALL
        SELECT 'Reilly' UNION ALL
        SELECT 'Remi' UNION ALL
        SELECT 'Remington' UNION ALL
        SELECT 'Remy' UNION ALL
        SELECT 'Rene' UNION ALL
        SELECT 'Renee' UNION ALL
        SELECT 'Revel' UNION ALL
        SELECT 'Ridley' UNION ALL
        SELECT 'Riley' UNION ALL
        SELECT 'Ryley' UNION ALL
        SELECT 'Rio' UNION ALL
        SELECT 'Ripley' UNION ALL
        SELECT 'River' UNION ALL
        SELECT 'Roan' UNION ALL
        SELECT 'Robin' UNION ALL
        SELECT 'Robyn' UNION ALL
        SELECT 'Rorey' UNION ALL
        SELECT 'Rory' UNION ALL
        SELECT 'Roux' UNION ALL
        SELECT 'Rowan' UNION ALL
        SELECT 'Royal' UNION ALL
        SELECT 'Rudy' UNION ALL
        SELECT 'Rumi' UNION ALL
        SELECT 'Ryan' UNION ALL
        SELECT 'Rylan' UNION ALL
        SELECT 'Sage' UNION ALL
        SELECT 'Sailor' UNION ALL
        SELECT 'Salem' UNION ALL
        SELECT 'Sam' UNION ALL
        SELECT 'Samar' UNION ALL
        SELECT 'Sasha' UNION ALL
        SELECT 'Sawyer' UNION ALL
        SELECT 'Scout' UNION ALL
        SELECT 'Sean' UNION ALL
        SELECT 'Seneca' UNION ALL
        SELECT 'Shae' UNION ALL
        SELECT 'Shannon' UNION ALL
        SELECT 'Shawn' UNION ALL
        SELECT 'Shay' UNION ALL
        SELECT 'Shiloh' UNION ALL
        SELECT 'Sidney' UNION ALL
        SELECT 'Sky' UNION ALL
        SELECT 'Skye' UNION ALL
        SELECT 'Skyler' UNION ALL
        SELECT 'Skylar' UNION ALL
        SELECT 'Sloan' UNION ALL
        SELECT 'Slone' UNION ALL
        SELECT 'Spencer' UNION ALL
        SELECT 'Sterling' UNION ALL
        SELECT 'Stirling' UNION ALL
        SELECT 'Stevie' UNION ALL
        SELECT 'Storm' UNION ALL
        SELECT 'Sunny' UNION ALL
        SELECT 'Sutton' UNION ALL
        SELECT 'Sydney' UNION ALL
        SELECT 'Tanner' UNION ALL
        SELECT 'Tate' UNION ALL
        SELECT 'Tatum' UNION ALL
        SELECT 'Taylen' UNION ALL
        SELECT 'Taylor' UNION ALL
        SELECT 'Tennessee' UNION ALL
        SELECT 'Tennyson' UNION ALL
        SELECT 'Teri' UNION ALL
        SELECT 'Terry' UNION ALL
        SELECT 'Texas' UNION ALL
        SELECT 'Timber' UNION ALL
        SELECT 'Tobin' UNION ALL
        SELECT 'Toby' UNION ALL
        SELECT 'Tobey' UNION ALL
        SELECT 'Tony' UNION ALL
        SELECT 'Toni' UNION ALL
        SELECT 'Tory' UNION ALL
        SELECT 'Tori' UNION ALL
        SELECT 'Tracy' UNION ALL
        SELECT 'Trinity' UNION ALL
        SELECT 'Tristan' UNION ALL
        SELECT 'Tru' UNION ALL
        SELECT 'Tyler' UNION ALL
        SELECT 'Umber' UNION ALL
        SELECT 'Unique' UNION ALL
        SELECT 'Val' UNION ALL
        SELECT 'Valentine' UNION ALL
        SELECT 'Vesper' UNION ALL
        SELECT 'Vick' UNION ALL
        SELECT 'Wallis' UNION ALL
        SELECT 'Wallace' UNION ALL
        SELECT 'Wesley' UNION ALL
        SELECT 'West' UNION ALL
        SELECT 'Whitney' UNION ALL
        SELECT 'Wilder' UNION ALL
        SELECT 'Winn' UNION ALL
        SELECT 'Wynn' UNION ALL
        SELECT 'Winter' UNION ALL
        SELECT 'Wisdom' UNION ALL
        SELECT 'Wren' UNION ALL
        SELECT 'Wyatt' UNION ALL
        SELECT 'Wynne' UNION ALL
        SELECT 'Xen' UNION ALL
        SELECT 'Xoan' UNION ALL
        SELECT 'Yael' UNION ALL
        SELECT 'Zephyr' UNION ALL
        SELECT 'Zion' UNION ALL
        SELECT 'Terry' UNION ALL
        SELECT 'Jamie' UNION ALL
        SELECT 'Francis' UNION ALL
        SELECT 'Kris' UNION ALL
        SELECT 'Charlie' UNION ALL
        SELECT 'Emerson' UNION ALL
        SELECT 'River' UNION ALL
        SELECT 'Tatum' UNION ALL
        SELECT 'Avery' UNION ALL
        SELECT 'Brooklyn' UNION ALL
        SELECT 'Campbell' UNION ALL
        SELECT 'Gray' UNION ALL
        SELECT 'Jordan' UNION ALL
        SELECT 'Morgan' UNION ALL
        SELECT 'Peyton' UNION ALL
        SELECT 'Reese' UNION ALL
        SELECT 'Riley' UNION ALL
        SELECT 'Robin' UNION ALL
        SELECT 'Rory' UNION ALL
        SELECT 'Sawyer' UNION ALL
        SELECT 'Sutton' UNION ALL
        SELECT 'Dakota' UNION ALL
        SELECT 'Parker' UNION ALL
        SELECT 'Quinn' UNION ALL
        SELECT 'Phoenix' UNION ALL
        SELECT 'Kendall' UNION ALL
        SELECT 'Harley' UNION ALL
        SELECT 'Blake' UNION ALL
        SELECT 'Hayden' UNION ALL
        SELECT 'Elliott' UNION ALL
        SELECT 'Karter' UNION ALL
        SELECT 'Taylor' UNION ALL
        SELECT 'Angel'
    ) np
;



INSERT INTO test.meta_namepart
SELECT
    (SELECT IFNULL(MAX(name_id), 0) FROM test.meta_namepart) + row_number() OVER(),
    np.*,
    'last name' AS name_part_type
FROM
    (
        SELECT 'Abawi' UNION ALL
        SELECT 'Abbington' UNION ALL
        SELECT 'Abbott' UNION ALL
        SELECT 'Abella' UNION ALL
        SELECT 'Abernathy' UNION ALL
        SELECT 'Abner' UNION ALL
        SELECT 'Abraham' UNION ALL
        SELECT 'Abrams' UNION ALL
        SELECT 'Abrell' UNION ALL
        SELECT 'Acampora' UNION ALL
        SELECT 'Acker' UNION ALL
        SELECT 'Ackerman' UNION ALL
        SELECT 'Ackroyd' UNION ALL
        SELECT 'Acosta' UNION ALL
        SELECT 'Acuff' UNION ALL
        SELECT 'Adair' UNION ALL
        SELECT 'Adams' UNION ALL
        SELECT 'Adara' UNION ALL
        SELECT 'Adderley' UNION ALL
        SELECT 'Adelson' UNION ALL
        SELECT 'Adkins' UNION ALL
        SELECT 'Adler' UNION ALL
        SELECT 'Agassi' UNION ALL
        SELECT 'Agholor' UNION ALL
        SELECT 'Agnello' UNION ALL
        SELECT 'Agnew' UNION ALL
        SELECT 'Agrippa' UNION ALL
        SELECT 'Aguilar' UNION ALL
        SELECT 'Aguillar' UNION ALL
        SELECT 'Aguirre' UNION ALL
        SELECT 'Aiken' UNION ALL
        SELECT 'Ainge' UNION ALL
        SELECT 'Akkad' UNION ALL
        SELECT 'Akuna' UNION ALL
        SELECT 'Albertson' UNION ALL
        SELECT 'Albright' UNION ALL
        SELECT 'Alcott' UNION ALL
        SELECT 'Aldrich' UNION ALL
        SELECT 'Alemán' UNION ALL
        SELECT 'Alexander' UNION ALL
        SELECT 'Algarotti' UNION ALL
        SELECT 'Alinsky' UNION ALL
        SELECT 'Allard' UNION ALL
        SELECT 'Allen' UNION ALL
        SELECT 'Allred' UNION ALL
        SELECT 'Almond' UNION ALL
        SELECT 'Alonso' UNION ALL
        SELECT 'Alstott' UNION ALL
        SELECT 'Alterio' UNION ALL
        SELECT 'Alvarado' UNION ALL
        SELECT 'Alvarez' UNION ALL
        SELECT 'Álvarez' UNION ALL
        SELECT 'Amado' UNION ALL
        SELECT 'Amherst' UNION ALL
        SELECT 'Anders' UNION ALL
        SELECT 'Anderson' UNION ALL
        SELECT 'Andrade' UNION ALL
        SELECT 'Andruzzi' UNION ALL
        SELECT 'Angle' UNION ALL
        SELECT 'Annenberg' UNION ALL
        SELECT 'Antrican' UNION ALL
        SELECT 'Aoki' UNION ALL
        SELECT 'Apatow' UNION ALL
        SELECT 'Archeletta' UNION ALL
        SELECT 'Archer' UNION ALL
        SELECT 'Arellano' UNION ALL
        SELECT 'Argento' UNION ALL
        SELECT 'Arias' UNION ALL
        SELECT 'Armani' UNION ALL
        SELECT 'Armas' UNION ALL
        SELECT 'Armstrong' UNION ALL
        SELECT 'Arrhenius' UNION ALL
        SELECT 'Arrington' UNION ALL
        SELECT 'Arrowood' UNION ALL
        SELECT 'Asola' UNION ALL
        SELECT 'Asterio' UNION ALL
        SELECT 'Atchley' UNION ALL
        SELECT 'Atkinson' UNION ALL
        SELECT 'Attard' UNION ALL
        SELECT 'Atwater' UNION ALL
        SELECT 'Atwood' UNION ALL
        SELECT 'Austin' UNION ALL
        SELECT 'Ávalos' UNION ALL
        SELECT 'Averescu' UNION ALL
        SELECT 'Ávila' UNION ALL
        SELECT 'Axworthy' UNION ALL
        SELECT 'Ayala' UNION ALL
        SELECT 'Ayesa' UNION ALL
        SELECT 'Bailey' UNION ALL
        SELECT 'Baker' UNION ALL
        SELECT 'Bald' UNION ALL
        SELECT 'Baldwin' UNION ALL
        SELECT 'Ballard' UNION ALL
        SELECT 'Bamberger' UNION ALL
        SELECT 'Bandini' UNION ALL
        SELECT 'Banner' UNION ALL
        SELECT 'Banu' UNION ALL
        SELECT 'Barajas' UNION ALL
        SELECT 'Barks' UNION ALL
        SELECT 'Barnes' UNION ALL
        SELECT 'Barrera' UNION ALL
        SELECT 'Barrick' UNION ALL
        SELECT 'Barrios' UNION ALL
        SELECT 'Bartley' UNION ALL
        SELECT 'Batch' UNION ALL
        SELECT 'Bauer' UNION ALL
        SELECT 'Bautista' UNION ALL
        SELECT 'Becerra' UNION ALL
        SELECT 'Beebe' UNION ALL
        SELECT 'Beeks' UNION ALL
        SELECT 'Belinski' UNION ALL
        SELECT 'Bell' UNION ALL
        SELECT 'Bellisario' UNION ALL
        SELECT 'Belt' UNION ALL
        SELECT 'Beltrán' UNION ALL
        SELECT 'Bender' UNION ALL
        SELECT 'Benítez' UNION ALL
        SELECT 'Bennett' UNION ALL
        SELECT 'Benoit' UNION ALL
        SELECT 'Bensen' UNION ALL
        SELECT 'Benton' UNION ALL
        SELECT 'Benwikere' UNION ALL
        SELECT 'Benz' UNION ALL
        SELECT 'Berman' UNION ALL
        SELECT 'Bernthal' UNION ALL
        SELECT 'Berry' UNION ALL
        SELECT 'Bersa' UNION ALL
        SELECT 'Best' UNION ALL
        SELECT 'Bester' UNION ALL
        SELECT 'Bettis' UNION ALL
        SELECT 'Bezos' UNION ALL
        SELECT 'Biddle' UNION ALL
        SELECT 'Biles' UNION ALL
        SELECT 'BInda' UNION ALL
        SELECT 'Binion' UNION ALL
        SELECT 'Bishop' UNION ALL
        SELECT 'Bisley' UNION ALL
        SELECT 'Bixby' UNION ALL
        SELECT 'Blanco' UNION ALL
        SELECT 'Blanks' UNION ALL
        SELECT 'Blaustein' UNION ALL
        SELECT 'Blixt' UNION ALL
        SELECT 'Bloch' UNION ALL
        SELECT 'Blood' UNION ALL
        SELECT 'Blow' UNION ALL
        SELECT 'Bobusic' UNION ALL
        SELECT 'Bogaerts' UNION ALL
        SELECT 'Boggs' UNION ALL
        SELECT 'Boldon' UNION ALL
        SELECT 'Bonanno' UNION ALL
        SELECT 'Bonilla' UNION ALL
        SELECT 'Booker' UNION ALL
        SELECT 'Booth' UNION ALL
        SELECT 'Borden' UNION ALL
        SELECT 'Bosa' UNION ALL
        SELECT 'Bostwick' UNION ALL
        SELECT 'Botkin' UNION ALL
        SELECT 'Boulder' UNION ALL
        SELECT 'Boulware' UNION ALL
        SELECT 'Bourland' UNION ALL
        SELECT 'Bourne' UNION ALL
        SELECT 'Bowden' UNION ALL
        SELECT 'Bowman' UNION ALL
        SELECT 'Bowser' UNION ALL
        SELECT 'Boyle' UNION ALL
        SELECT 'Bozzelli' UNION ALL
        SELECT 'Bracco' UNION ALL
        SELECT 'Braddock' UNION ALL
        SELECT 'Bradshaw' UNION ALL
        SELECT 'Brager' UNION ALL
        SELECT 'Bragg' UNION ALL
        SELECT 'Brandt' UNION ALL
        SELECT 'Bravo' UNION ALL
        SELECT 'Bray' UNION ALL
        SELECT 'Brembilla' UNION ALL
        SELECT 'Brennan' UNION ALL
        SELECT 'Breslin' UNION ALL
        SELECT 'Briggs' UNION ALL
        SELECT 'Bright' UNION ALL
        SELECT 'Brinkmann' UNION ALL
        SELECT 'Bristow' UNION ALL
        SELECT 'Brooks' UNION ALL
        SELECT 'Brown' UNION ALL
        SELECT 'Brubaker' UNION ALL
        SELECT 'Brunt' UNION ALL
        SELECT 'Bryant' UNION ALL
        SELECT 'Buckner' UNION ALL
        SELECT 'Budreau' UNION ALL
        SELECT 'Bullard' UNION ALL
        SELECT 'Burris' UNION ALL
        SELECT 'Butler' UNION ALL
        SELECT 'Bynes' UNION ALL
        SELECT 'Byrne' UNION ALL
        SELECT 'Cabrera-Bello' UNION ALL
        SELECT 'Cabrera' UNION ALL
        SELECT 'Cagle' UNION ALL
        SELECT 'Cahill' UNION ALL
        SELECT 'Cain' UNION ALL
        SELECT 'Calaway' UNION ALL
        SELECT 'Calderón' UNION ALL
        SELECT 'Callahan' UNION ALL
        SELECT 'Camacho' UNION ALL
        SELECT 'Campbell' UNION ALL
        SELECT 'Campos' UNION ALL
        SELECT 'Candy' UNION ALL
        SELECT 'Cannon' UNION ALL
        SELECT 'Cano' UNION ALL
        SELECT 'Capra' UNION ALL
        SELECT 'Cárdenas' UNION ALL
        SELECT 'Carling' UNION ALL
        SELECT 'Carmichael' UNION ALL
        SELECT 'Carmona' UNION ALL
        SELECT 'Carney' UNION ALL
        SELECT 'Carrillo' UNION ALL
        SELECT 'Carter' UNION ALL
        SELECT 'Carver' UNION ALL
        SELECT 'Cassidy' UNION ALL
        SELECT 'Castañeda' UNION ALL
        SELECT 'Castellanos' UNION ALL
        SELECT 'Castillo' UNION ALL
        SELECT 'Castle' UNION ALL
        SELECT 'Castro' UNION ALL
        SELECT 'Cates' UNION ALL
        SELECT 'Cauley' UNION ALL
        SELECT 'Cave' UNION ALL
        SELECT 'Cayce' UNION ALL
        SELECT 'Caylor' UNION ALL
        SELECT 'Celino' UNION ALL
        SELECT 'Cena' UNION ALL
        SELECT 'Cents' UNION ALL
        SELECT 'Cervantes' UNION ALL
        SELECT 'Chadwick' UNION ALL
        SELECT 'Chalk' UNION ALL
        SELECT 'Challenger' UNION ALL
        SELECT 'Chalut' UNION ALL
        SELECT 'Chambers' UNION ALL
        SELECT 'Champ' UNION ALL
        SELECT 'Chatwin' UNION ALL
        SELECT 'Chavarría' UNION ALL
        SELECT 'Chávez' UNION ALL
        SELECT 'Cherry' UNION ALL
        SELECT 'Christie' UNION ALL
        SELECT 'Chung' UNION ALL
        SELECT 'Cirque' UNION ALL
        SELECT 'Cisneros' UNION ALL
        SELECT 'Clancy' UNION ALL
        SELECT 'Clark' UNION ALL
        SELECT 'Claxton' UNION ALL
        SELECT 'Clay' UNION ALL
        SELECT 'Cleary' UNION ALL
        SELECT 'Cleveland' UNION ALL
        SELECT 'Click' UNION ALL
        SELECT 'Cline' UNION ALL
        SELECT 'Coates' UNION ALL
        SELECT 'Cobb' UNION ALL
        SELECT 'Cobo' UNION ALL
        SELECT 'Coffey' UNION ALL
        SELECT 'Coffin' UNION ALL
        SELECT 'Cogdill' UNION ALL
        SELECT 'Coggins' UNION ALL
        SELECT 'Cohen' UNION ALL
        SELECT 'Coin' UNION ALL
        SELECT 'Collins' UNION ALL
        SELECT 'Colt' UNION ALL
        SELECT 'Coltrane' UNION ALL
        SELECT 'Conard' UNION ALL
        SELECT 'Conklin' UNION ALL
        SELECT 'Connelly' UNION ALL
        SELECT 'Conti' UNION ALL
        SELECT 'Contreras' UNION ALL
        SELECT 'Cook' UNION ALL
        SELECT 'Coolidge' UNION ALL
        SELECT 'Cooper' UNION ALL
        SELECT 'Copeland' UNION ALL
        SELECT 'Coppens' UNION ALL
        SELECT 'Córdova' UNION ALL
        SELECT 'Corona' UNION ALL
        SELECT 'Cortez' UNION ALL
        SELECT 'Cortse' UNION ALL
        SELECT 'Costner' UNION ALL
        SELECT 'Cotheran' UNION ALL
        SELECT 'Coulter' UNION ALL
        SELECT 'Cox' UNION ALL
        SELECT 'Crabtree' UNION ALL
        SELECT 'Craggs' UNION ALL
        SELECT 'Cranham' UNION ALL
        SELECT 'Crassus' UNION ALL
        SELECT 'Crawford' UNION ALL
        SELECT 'Creed' UNION ALL
        SELECT 'Creel' UNION ALL
        SELECT 'Crespo' UNION ALL
        SELECT 'Crisp' UNION ALL
        SELECT 'Crisper' UNION ALL
        SELECT 'Cross' UNION ALL
        SELECT 'Crowley' UNION ALL
        SELECT 'Crusher' UNION ALL
        SELECT 'Cruz' UNION ALL
        SELECT 'Cuevas' UNION ALL
        SELECT 'Cugat' UNION ALL
        SELECT 'Cullen' UNION ALL
        SELECT 'Cunningham' UNION ALL
        SELECT 'Curio' UNION ALL
        SELECT 'Curry' UNION ALL
        SELECT 'Cutler' UNION ALL
        SELECT 'Cyrus' UNION ALL
        SELECT 'Dabney' UNION ALL
        SELECT 'Daddario' UNION ALL
        SELECT 'Dahl' UNION ALL
        SELECT 'Dallesandro' UNION ALL
        SELECT 'Dalton' UNION ALL
        SELECT 'Dandridge' UNION ALL
        SELECT 'Danton' UNION ALL
        SELECT 'Darby' UNION ALL
        SELECT 'Dark' UNION ALL
        SELECT 'Davenport' UNION ALL
        SELECT 'Dávila' UNION ALL
        SELECT 'Davis' UNION ALL
        SELECT 'Dawkins' UNION ALL
        SELECT 'Day' UNION ALL
        SELECT 'de Jesús' UNION ALL
        SELECT 'de la Cruz' UNION ALL
        SELECT 'De La Rosa' UNION ALL
        SELECT 'de León' UNION ALL
        SELECT 'Decarlo' UNION ALL
        SELECT 'Decker' UNION ALL
        SELECT 'Delgado' UNION ALL
        SELECT 'Delpy' UNION ALL
        SELECT 'Dempsey' UNION ALL
        SELECT 'Denton' UNION ALL
        SELECT 'Denver' UNION ALL
        SELECT 'Derbyshire' UNION ALL
        SELECT 'Devereaux' UNION ALL
        SELECT 'Devlin' UNION ALL
        SELECT 'Diamond' UNION ALL
        SELECT 'Diaz' UNION ALL
        SELECT 'Díaz' UNION ALL
        SELECT 'Dickerson' UNION ALL
        SELECT 'Ditka' UNION ALL
        SELECT 'Dixon' UNION ALL
        SELECT 'Dobermann' UNION ALL
        SELECT 'Dobra' UNION ALL
        SELECT 'Dodge' UNION ALL
        SELECT 'Dominguez' UNION ALL
        SELECT 'Domínguez' UNION ALL
        SELECT 'Donahue' UNION ALL
        SELECT 'Donnelly' UNION ALL
        SELECT 'Donovan' UNION ALL
        SELECT 'Dooley' UNION ALL
        SELECT 'Draper' UNION ALL
        SELECT 'Drewitt' UNION ALL
        SELECT 'Driskel' UNION ALL
        SELECT 'Driver' UNION ALL
        SELECT 'Duarte' UNION ALL
        SELECT 'Dubois' UNION ALL
        SELECT 'Dufner' UNION ALL
        SELECT 'Dukas' UNION ALL
        SELECT 'Dumont' UNION ALL
        SELECT 'Dunlop' UNION ALL
        SELECT 'Durán' UNION ALL
        SELECT 'Dwyer' UNION ALL
        SELECT 'Dyer' UNION ALL
        SELECT 'Earp' UNION ALL
        SELECT 'Earwood' UNION ALL
        SELECT 'Eastwood' UNION ALL
        SELECT 'Ebersol' UNION ALL
        SELECT 'Eberstark' UNION ALL
        SELECT 'Edge' UNION ALL
        SELECT 'Edgeworth' UNION ALL
        SELECT 'Edwards' UNION ALL
        SELECT 'Egan' UNION ALL
        SELECT 'Ekker' UNION ALL
        SELECT 'Elder' UNION ALL
        SELECT 'Eldridge' UNION ALL
        SELECT 'Ellenburg' UNION ALL
        SELECT 'Ellerbrock' UNION ALL
        SELECT 'Elway' UNION ALL
        SELECT 'Endo' UNION ALL
        SELECT 'England' UNION ALL
        SELECT 'Enríquez' UNION ALL
        SELECT 'Epps' UNION ALL
        SELECT 'Escobar' UNION ALL
        SELECT 'Eslinger' UNION ALL
        SELECT 'Esparza' UNION ALL
        SELECT 'Espinoza' UNION ALL
        SELECT 'Esquivel' UNION ALL
        SELECT 'Estrada' UNION ALL
        SELECT 'Etter' UNION ALL
        SELECT 'Eubanks' UNION ALL
        SELECT 'Evans' UNION ALL
        SELECT 'Everhart' UNION ALL
        SELECT 'Everson' UNION ALL
        SELECT 'Evert' UNION ALL
        SELECT 'Faddis' UNION ALL
        SELECT 'Fairbanks' UNION ALL
        SELECT 'Fairchild' UNION ALL
        SELECT 'Fangio' UNION ALL
        SELECT 'Farley' UNION ALL
        SELECT 'Farrell' UNION ALL
        SELECT 'Fassbinder' UNION ALL
        SELECT 'Fawcett' UNION ALL
        SELECT 'Fawzi' UNION ALL
        SELECT 'Fenner' UNION ALL
        SELECT 'Fenton' UNION ALL
        SELECT 'Ferber' UNION ALL
        SELECT 'Ferenz' UNION ALL
        SELECT 'Ferguson' UNION ALL
        SELECT 'Fernández' UNION ALL
        SELECT 'Figueroa' UNION ALL
        SELECT 'Finau' UNION ALL
        SELECT 'Finch' UNION ALL
        SELECT 'Finchum' UNION ALL
        SELECT 'Fingermann' --UNION ALL
    ) np
;


INSERT INTO test.meta_namepart
SELECT
    (SELECT IFNULL(MAX(name_id), 0) FROM test.meta_namepart) + row_number() OVER(),
    np.*,
    'last name' AS name_part_type
FROM
    (
        SELECT 'Finn' UNION ALL
        SELECT 'Fisher' UNION ALL
        SELECT 'Fishman' UNION ALL
        SELECT 'Fissolo' UNION ALL
        SELECT 'Fitzgerald' UNION ALL
        SELECT 'Fitzpatrick' UNION ALL
        SELECT 'Flagg' UNION ALL
        SELECT 'Flair' UNION ALL
        SELECT 'Flanagan' UNION ALL
        SELECT 'Fleetwood' UNION ALL
        SELECT 'Fleiss' UNION ALL
        SELECT 'Fletcher' UNION ALL
        SELECT 'Flood' UNION ALL
        SELECT 'Floquet' UNION ALL
        SELECT 'Flores' UNION ALL
        SELECT 'Floris' UNION ALL
        SELECT 'Flynn' UNION ALL
        SELECT 'Fogerty' UNION ALL
        SELECT 'Foley' UNION ALL
        SELECT 'Fong' UNION ALL
        SELECT 'Fontana' UNION ALL
        SELECT 'Foster' UNION ALL
        SELECT 'Franco' UNION ALL
        SELECT 'Freed' UNION ALL
        SELECT 'Freeman' UNION ALL
        SELECT 'Freeze' UNION ALL
        SELECT 'Froning' UNION ALL
        SELECT 'Frost' UNION ALL
        SELECT 'Fsik' UNION ALL
        SELECT 'Fuentes' UNION ALL
        SELECT 'Fugger' UNION ALL
        SELECT 'Fullbright' UNION ALL
        SELECT 'Fuller' UNION ALL
        SELECT 'Furyk' UNION ALL
        SELECT 'Future' UNION ALL
        SELECT 'Gabbard' UNION ALL
        SELECT 'Gabel' UNION ALL
        SELECT 'Gaither' UNION ALL
        SELECT 'Galindo' UNION ALL
        SELECT 'Gallagher' UNION ALL
        SELECT 'Gallardo' UNION ALL
        SELECT 'Gallegos' UNION ALL
        SELECT 'Galván' UNION ALL
        SELECT 'Gannon' UNION ALL
        SELECT 'Garcia' UNION ALL
        SELECT 'García' UNION ALL
        SELECT 'Gardel' UNION ALL
        SELECT 'Gardner' UNION ALL
        SELECT 'Garza' UNION ALL
        SELECT 'Gearey' UNION ALL
        SELECT 'Geel' UNION ALL
        SELECT 'Gellar' UNION ALL
        SELECT 'Gelpi' UNION ALL
        SELECT 'Geske' UNION ALL
        SELECT 'Gilardi' UNION ALL
        SELECT 'Gillis' UNION ALL
        SELECT 'Glaser' UNION ALL
        SELECT 'Glass' UNION ALL
        SELECT 'Gleason' UNION ALL
        SELECT 'Glick' UNION ALL
        SELECT 'Glover' UNION ALL
        SELECT 'Glunt' UNION ALL
        SELECT 'Goddard' UNION ALL
        SELECT 'Golden' UNION ALL
        SELECT 'Gomez' UNION ALL
        SELECT 'Gómez' UNION ALL
        SELECT 'Gonzales' UNION ALL
        SELECT 'Gonzalez' UNION ALL
        SELECT 'González' UNION ALL
        SELECT 'Goodwin' UNION ALL
        SELECT 'Gore' UNION ALL
        SELECT 'Gotti' UNION ALL
        SELECT 'Goulding' UNION ALL
        SELECT 'Graber' UNION ALL
        SELECT 'Gray' UNION ALL
        SELECT 'Green' UNION ALL
        SELECT 'Greenway' UNION ALL
        SELECT 'Greer' UNION ALL
        SELECT 'Grell' UNION ALL
        SELECT 'Gribble' UNION ALL
        SELECT 'Griffith' UNION ALL
        SELECT 'Griffo' UNION ALL
        SELECT 'Grimes' UNION ALL
        SELECT 'Grizzly' UNION ALL
        SELECT 'Grooms' UNION ALL
        SELECT 'Grubbs' UNION ALL
        SELECT 'Guerra' UNION ALL
        SELECT 'Guerrero' UNION ALL
        SELECT 'Guest' UNION ALL
        SELECT 'Guevara' UNION ALL
        SELECT 'Gundlach' UNION ALL
        SELECT 'Gutierrez' UNION ALL
        SELECT 'Gutiérrez' UNION ALL
        SELECT 'Guzmán' UNION ALL
        SELECT 'Hadwin' UNION ALL
        SELECT 'Hale' UNION ALL
        SELECT 'Hall' UNION ALL
        SELECT 'Halleck' UNION ALL
        SELECT 'Halliwell' UNION ALL
        SELECT 'Hamilton' UNION ALL
        SELECT 'Hammer' UNION ALL
        SELECT 'Hammond' UNION ALL
        SELECT 'Hanifin' UNION ALL
        SELECT 'Hardin' UNION ALL
        SELECT 'Hardison' UNION ALL
        SELECT 'Hardy' UNION ALL
        SELECT 'Harker' UNION ALL
        SELECT 'Harper' UNION ALL
        SELECT 'Harris' UNION ALL
        SELECT 'Hart' UNION ALL
        SELECT 'Hartman' UNION ALL
        SELECT 'Hartsell' UNION ALL
        SELECT 'Harvick' UNION ALL
        SELECT 'Hatcher' UNION ALL
        SELECT 'Hatton' UNION ALL
        SELECT 'Hawk' UNION ALL
        SELECT 'Haystack' UNION ALL
        SELECT 'Head' UNION ALL
        SELECT 'Healy' UNION ALL
        SELECT 'Heers' UNION ALL
        SELECT 'Helbig' UNION ALL
        SELECT 'Heller' UNION ALL
        SELECT 'Hembree' UNION ALL
        SELECT 'Hemmings' UNION ALL
        SELECT 'Henderson' UNION ALL
        SELECT 'Henn' UNION ALL
        SELECT 'Hernandez' UNION ALL
        SELECT 'Hernández' UNION ALL
        SELECT 'Herrera' UNION ALL
        SELECT 'Hess' UNION ALL
        SELECT 'Hester' UNION ALL
        SELECT 'Hibben' UNION ALL
        SELECT 'Hickey' UNION ALL
        SELECT 'Higgins' UNION ALL
        SELECT 'Hightower' UNION ALL
        SELECT 'Hill' UNION ALL
        SELECT 'Hilliard' UNION ALL
        SELECT 'Hindley' UNION ALL
        SELECT 'Hitchcock' UNION ALL
        SELECT 'Hitchens' UNION ALL
        SELECT 'Hoagland' UNION ALL
        SELECT 'Hobbs' UNION ALL
        SELECT 'Hobgood' UNION ALL
        SELECT 'Hodder' UNION ALL
        SELECT 'Hogan' UNION ALL
        SELECT 'Hokoda' UNION ALL
        SELECT 'Holiday' UNION ALL
        SELECT 'Holland' UNION ALL
        SELECT 'Homa' UNION ALL
        SELECT 'Hood' UNION ALL
        SELECT 'Hooper' UNION ALL
        SELECT 'Horry' UNION ALL
        SELECT 'Hostetler' UNION ALL
        SELECT 'Howard' UNION ALL
        SELECT 'Howell' UNION ALL
        SELECT 'Huerta' UNION ALL
        SELECT 'Huffman' UNION ALL
        SELECT 'Hughes' UNION ALL
        SELECT 'Hull' UNION ALL
        SELECT 'Humber' UNION ALL
        SELECT 'Husher' UNION ALL
        SELECT 'Hutton' UNION ALL
        SELECT 'Huxley' UNION ALL
        SELECT 'Huxx' UNION ALL
        SELECT 'Hyde' UNION ALL
        SELECT 'Ibach' UNION ALL
        SELECT 'Ibara' UNION ALL
        SELECT 'Ibarra' UNION ALL
        SELECT 'Idelson' UNION ALL
        SELECT 'Inch' UNION ALL
        SELECT 'Ingram' UNION ALL
        SELECT 'Inoki' UNION ALL
        SELECT 'Irons' UNION ALL
        SELECT 'Irvin' UNION ALL
        SELECT 'Irwin' UNION ALL
        SELECT 'Ishikawa' UNION ALL
        SELECT 'Ivanenko' UNION ALL
        SELECT 'Ives' UNION ALL
        SELECT 'Jackman' UNION ALL
        SELECT 'Jackson' UNION ALL
        SELECT 'Jagger' UNION ALL
        SELECT 'James' UNION ALL
        SELECT 'Jameson' UNION ALL
        SELECT 'Jammer' UNION ALL
        SELECT 'Jenkins' UNION ALL
        SELECT 'Jessup' UNION ALL
        SELECT 'Jett' UNION ALL
        SELECT 'Jiménez' UNION ALL
        SELECT 'Jingle' UNION ALL
        SELECT 'Jishu' UNION ALL
        SELECT 'Johnson' UNION ALL
        SELECT 'Jones' UNION ALL
        SELECT 'Juárez' UNION ALL
        SELECT 'Jurado' UNION ALL
        SELECT 'Kaminsky' UNION ALL
        SELECT 'Katts' UNION ALL
        SELECT 'Kaufman' UNION ALL
        SELECT 'Keagan' UNION ALL
        SELECT 'Keating' UNION ALL
        SELECT 'Keats' UNION ALL
        SELECT 'Keene' UNION ALL
        SELECT 'Keller' UNION ALL
        SELECT 'Kellett' UNION ALL
        SELECT 'Kelly' UNION ALL
        SELECT 'Kenny' UNION ALL
        SELECT 'Keogh' UNION ALL
        SELECT 'Kerrigan' UNION ALL
        SELECT 'Kersey' UNION ALL
        SELECT 'Kershaw' UNION ALL
        SELECT 'Kessler' UNION ALL
        SELECT 'Kestrel' UNION ALL
        SELECT 'Keys' UNION ALL
        SELECT 'Kicklighter' UNION ALL
        SELECT 'Kilmer' UNION ALL
        SELECT 'Kincaid' UNION ALL
        SELECT 'Kinder' UNION ALL
        SELECT 'King' UNION ALL
        SELECT 'Kipps' UNION ALL
        SELECT 'Kirby' UNION ALL
        SELECT 'Kitt' UNION ALL
        SELECT 'Klecko' UNION ALL
        SELECT 'Knox' UNION ALL
        SELECT 'Kobayashi' UNION ALL
        SELECT 'Koch' UNION ALL
        SELECT 'Koker' UNION ALL
        SELECT 'Koo' UNION ALL
        SELECT 'Kotek' UNION ALL
        SELECT 'Koufax' UNION ALL
        SELECT 'Kubiak' UNION ALL
        SELECT 'Kuchar' UNION ALL
        SELECT 'Kulikov' UNION ALL
        SELECT 'Kumara' UNION ALL
        SELECT 'Lacer' UNION ALL
        SELECT 'Lacroix' UNION ALL
        SELECT 'Lafferty' UNION ALL
        SELECT 'Laker' UNION ALL
        SELECT 'Lambert' UNION ALL
        SELECT 'Landis' UNION ALL
        SELECT 'Lara' UNION ALL
        SELECT 'Lattimore' UNION ALL
        SELECT 'Laudermilk' UNION ALL
        SELECT 'Lawler' UNION ALL
        SELECT 'Lazenby' UNION ALL
        SELECT 'Leary' UNION ALL
        SELECT 'Leaves' UNION ALL
        SELECT 'Lecter' UNION ALL
        SELECT 'Ledford' UNION ALL
        SELECT 'Ledger' UNION ALL
        SELECT 'Lee' UNION ALL
        SELECT 'Leishman' UNION ALL
        SELECT 'LeMay' UNION ALL
        SELECT 'Lentz' UNION ALL
        SELECT 'León' UNION ALL
        SELECT 'Lesnar' UNION ALL
        SELECT 'Lewis' UNION ALL
        SELECT 'Lichter' UNION ALL
        SELECT 'Lipman' UNION ALL
        SELECT 'Liston' UNION ALL
        SELECT 'Litvak' UNION ALL
        SELECT 'Locke' UNION ALL
        SELECT 'Lomax' UNION ALL
        SELECT 'Lombardo' UNION ALL
        SELECT 'London' UNION ALL
        SELECT 'Londos' UNION ALL
        SELECT 'Long' UNION ALL
        SELECT 'Longwood' UNION ALL
        SELECT 'Lopez' UNION ALL
        SELECT 'López' UNION ALL
        SELECT 'Lords' UNION ALL
        SELECT 'Lott' UNION ALL
        SELECT 'Lovecraft' UNION ALL
        SELECT 'Lovejoy' UNION ALL
        SELECT 'Lovin' UNION ALL
        SELECT 'Lozano' UNION ALL
        SELECT 'Lucchesi' UNION ALL
        SELECT 'Lugo' UNION ALL
        SELECT 'Luna' UNION ALL
        SELECT 'Lynch' UNION ALL
        SELECT 'Mackey' UNION ALL
        SELECT 'Macklin' UNION ALL
        SELECT 'Maddox' UNION ALL
        SELECT 'Magaña' UNION ALL
        SELECT 'Magnusson' UNION ALL
        SELECT 'Mahan' UNION ALL
        SELECT 'Maker' UNION ALL
        SELECT 'Maldonado' UNION ALL
        SELECT 'Malenko' UNION ALL
        SELECT 'Malfoy' UNION ALL
        SELECT 'Malik' UNION ALL
        SELECT 'Mallory' UNION ALL
        SELECT 'Mannix' UNION ALL
        SELECT 'Mantooth' UNION ALL
        SELECT 'Manus' UNION ALL
        SELECT 'Marín' UNION ALL
        SELECT 'Marino' UNION ALL
        SELECT 'Marley' UNION ALL
        SELECT 'Márquez' UNION ALL
        SELECT 'Marsh' UNION ALL
        SELECT 'Martin' UNION ALL
        SELECT 'Martinez' UNION ALL
        SELECT 'Martínez' UNION ALL
        SELECT 'Mason' UNION ALL
        SELECT 'Massey' UNION ALL
        SELECT 'Matisse' UNION ALL
        SELECT 'Mattingly' UNION ALL
        SELECT 'McCabe' UNION ALL
        SELECT 'McGee' UNION ALL
        SELECT 'McGillicutty' UNION ALL
        SELECT 'McKay' UNION ALL
        SELECT 'McKnight' UNION ALL
        SELECT 'McNamara' UNION ALL
        SELECT 'Medina' UNION ALL
        SELECT 'Meer' UNION ALL
        SELECT 'Meilyr' UNION ALL
        SELECT 'Mejía' UNION ALL
        SELECT 'Méndez' UNION ALL
        SELECT 'Mendoza' UNION ALL
        SELECT 'Mercado' UNION ALL
        SELECT 'Mercer' UNION ALL
        SELECT 'Merchant' UNION ALL
        SELECT 'Messi' UNION ALL
        SELECT 'Metcalf' UNION ALL
        SELECT 'Metz' UNION ALL
        SELECT 'Meza' UNION ALL
        SELECT 'Miller' UNION ALL
        SELECT 'Minter' UNION ALL
        SELECT 'Mintz' UNION ALL
        SELECT 'Miranda' UNION ALL
        SELECT 'Mitchell' UNION ALL
        SELECT 'Moffett' UNION ALL
        SELECT 'Molina' UNION ALL
        SELECT 'Molinari' UNION ALL
        SELECT 'Montero' UNION ALL
        SELECT 'Montes' UNION ALL
        SELECT 'Montoya' UNION ALL
        SELECT 'Moody' UNION ALL
        SELECT 'Mooney' UNION ALL
        SELECT 'Moore' UNION ALL
        SELECT 'Mora' UNION ALL
        SELECT 'Morales' UNION ALL
        SELECT 'Moreau' UNION ALL
        SELECT 'Moreno' UNION ALL
        SELECT 'Morgan' UNION ALL
        SELECT 'Morikowa' UNION ALL
        SELECT 'Morozov' UNION ALL
        SELECT 'Morris' UNION ALL
        SELECT 'Morrison' UNION ALL
        SELECT 'Morrissey' UNION ALL
        SELECT 'Moses' UNION ALL
        SELECT 'Motter' UNION ALL
        SELECT 'Mudd' UNION ALL
        SELECT 'Mulder' UNION ALL
        SELECT 'Mullard' UNION ALL
        SELECT 'Mullinax' UNION ALL
        SELECT 'Muñoz' UNION ALL
        SELECT 'Munson' UNION ALL
        SELECT 'Murdock' UNION ALL
        SELECT 'Murillo' UNION ALL
        SELECT 'Murphy' UNION ALL
        SELECT 'Murray' UNION ALL
        SELECT 'Myers' UNION ALL
        SELECT 'Nabor' UNION ALL
        SELECT 'Naillon' UNION ALL
        SELECT 'Namath' UNION ALL
        SELECT 'Napier' UNION ALL
        SELECT 'Nash' UNION ALL
        SELECT 'Nava' UNION ALL
        SELECT 'Navarrete' UNION ALL
        SELECT 'Navarro' UNION ALL
        SELECT 'Necessary' UNION ALL
        SELECT 'Neiderman' UNION ALL
        SELECT 'Nejem' UNION ALL
        SELECT 'Nelson' UNION ALL
        SELECT 'Nguyen' UNION ALL
        SELECT 'Nicely' UNION ALL
        SELECT 'Nighy' UNION ALL
        SELECT 'Niles' UNION ALL
        SELECT 'Nolan' UNION ALL
        SELECT 'Noonan' UNION ALL
        SELECT 'Norris' UNION ALL
        SELECT 'Norwood' UNION ALL
        SELECT 'Novak' UNION ALL
        SELECT 'Núñez' UNION ALL
        SELECT 'Nunley' UNION ALL
        SELECT 'Nunn' UNION ALL
        SELECT 'Nygard' UNION ALL
        SELECT 'Nyland' UNION ALL
        SELECT 'Nystrom' --UNION ALL
    ) np
;



INSERT INTO test.meta_namepart
SELECT
    (SELECT IFNULL(MAX(name_id), 0) FROM test.meta_namepart) + row_number() OVER(),
    np.*,
    'last name' AS name_part_type
FROM
    (
        SELECT '''O'Bannon''' UNION ALL
        SELECT '''O'Brien''' UNION ALL
        SELECT '''O'Donnell''' UNION ALL
        SELECT '''O'Leary''' UNION ALL
        SELECT '''O'Malley''' UNION ALL
        SELECT '''O'Rourke''' UNION ALL
        SELECT 'Oakley' UNION ALL
        SELECT 'Oaks' UNION ALL
        SELECT 'Oberman' UNION ALL
        SELECT 'Ochoa' UNION ALL
        SELECT 'October' UNION ALL
        SELECT 'Odenkirk' UNION ALL
        SELECT 'Oduya' UNION ALL
        SELECT 'Ogden' UNION ALL
        SELECT 'Ogle' UNION ALL
        SELECT 'Ogletree' UNION ALL
        SELECT 'Oldman' UNION ALL
        SELECT 'Olivares' UNION ALL
        SELECT 'Ollenrenshaw' UNION ALL
        SELECT 'Olson' UNION ALL
        SELECT 'Olvera' UNION ALL
        SELECT 'Onassis' UNION ALL
        SELECT 'Opilio' UNION ALL
        SELECT 'Orozco' UNION ALL
        SELECT 'Orr' UNION ALL
        SELECT 'Ortega' UNION ALL
        SELECT 'Ortiz' UNION ALL
        SELECT 'Ortíz' UNION ALL
        SELECT 'Orton' UNION ALL
        SELECT 'Oshima' UNION ALL
        SELECT 'Osorio' UNION ALL
        SELECT 'Oswald' UNION ALL
        SELECT 'Ottinger' UNION ALL
        SELECT 'Otto' UNION ALL
        SELECT 'Overholt' UNION ALL
        SELECT 'Owusu' UNION ALL
        SELECT 'Ozu' UNION ALL
        SELECT 'Pacheco' UNION ALL
        SELECT 'Padilla' UNION ALL
        SELECT 'Paisley' UNION ALL
        SELECT 'Palacios' UNION ALL
        SELECT 'Palmer' UNION ALL
        SELECT 'Panera' UNION ALL
        SELECT 'Paredes' UNION ALL
        SELECT 'Parker' UNION ALL
        SELECT 'Patnick' UNION ALL
        SELECT 'Patterson' UNION ALL
        SELECT 'Pavlov' UNION ALL
        SELECT 'Pawar' UNION ALL
        SELECT 'Paxton' UNION ALL
        SELECT 'Paz' UNION ALL
        SELECT 'Peck' UNION ALL
        SELECT 'Pell' UNION ALL
        SELECT 'Peña' UNION ALL
        SELECT 'Pepin' UNION ALL
        SELECT 'Perabo' UNION ALL
        SELECT 'Peralta' UNION ALL
        SELECT 'Perez' UNION ALL
        SELECT 'Pérez' UNION ALL
        SELECT 'Perkins' UNION ALL
        SELECT 'Perrin' UNION ALL
        SELECT 'Perry' UNION ALL
        SELECT 'Peterson' UNION ALL
        SELECT 'Phillips' UNION ALL
        SELECT 'Pickering' UNION ALL
        SELECT 'Pinder' UNION ALL
        SELECT 'Pineda' UNION ALL
        SELECT 'Pinzer' UNION ALL
        SELECT 'Piper' UNION ALL
        SELECT 'Pitcher' UNION ALL
        SELECT 'Pittman' UNION ALL
        SELECT 'Pladino' UNION ALL
        SELECT 'Platt' UNION ALL
        SELECT 'Plunkett' UNION ALL
        SELECT 'Pointer' UNION ALL
        SELECT 'Pollock' UNION ALL
        SELECT 'Ponce' UNION ALL
        SELECT 'Pope' UNION ALL
        SELECT 'Porter' UNION ALL
        SELECT 'Portillo' UNION ALL
        SELECT 'Portis' UNION ALL
        SELECT 'Posada' UNION ALL
        SELECT 'Post' UNION ALL
        SELECT 'Poston' UNION ALL
        SELECT 'Powell' UNION ALL
        SELECT 'Powers' UNION ALL
        SELECT 'Prado' UNION ALL
        SELECT 'Prescott' UNION ALL
        SELECT 'Previn' UNION ALL
        SELECT 'Price' UNION ALL
        SELECT 'Prunk' UNION ALL
        SELECT 'Puller' UNION ALL
        SELECT 'Pulman' UNION ALL
        SELECT 'Punch' UNION ALL
        SELECT 'Putnam' UNION ALL
        SELECT 'Qua' UNION ALL
        SELECT 'Quaice' UNION ALL
        SELECT 'Quaid' UNION ALL
        SELECT 'Quall' UNION ALL
        SELECT 'Quan' UNION ALL
        SELECT 'Quarters' UNION ALL
        SELECT 'Qugg' UNION ALL
        SELECT 'Quick' UNION ALL
        SELECT 'Quimby' UNION ALL
        SELECT 'Quinn' UNION ALL
        SELECT 'Quint' UNION ALL
        SELECT 'Quintero' UNION ALL
        SELECT 'Quirico' UNION ALL
        SELECT 'Quiróz' UNION ALL
        SELECT 'Quivers' UNION ALL
        SELECT 'Race' UNION ALL
        SELECT 'Radiguet' UNION ALL
        SELECT 'Rafferty' UNION ALL
        SELECT 'Rafus' UNION ALL
        SELECT 'Rainwater' UNION ALL
        SELECT 'Ramirez' UNION ALL
        SELECT 'Ramírez' UNION ALL
        SELECT 'Ramos' UNION ALL
        SELECT 'Rand' UNION ALL
        SELECT 'Rangel' UNION ALL
        SELECT 'Reader' UNION ALL
        SELECT 'Reagan' UNION ALL
        SELECT 'Redgrave' UNION ALL
        SELECT 'Redman' UNION ALL
        SELECT 'Reece' UNION ALL
        SELECT 'Reed' UNION ALL
        SELECT 'Reinhart' UNION ALL
        SELECT 'Renfro' UNION ALL
        SELECT 'Renshaw' UNION ALL
        SELECT 'Reséndiz' UNION ALL
        SELECT 'Reyes' UNION ALL
        SELECT 'Reynoso' UNION ALL
        SELECT 'Rhodes' UNION ALL
        SELECT 'Richardson' UNION ALL
        SELECT 'Richter' UNION ALL
        SELECT 'Riddle' UNION ALL
        SELECT 'Rifkin' UNION ALL
        SELECT 'Rigby' UNION ALL
        SELECT 'Riggs' UNION ALL
        SELECT 'Riker' UNION ALL
        SELECT 'Ríos' UNION ALL
        SELECT 'Ripa' UNION ALL
        SELECT 'Ripley' UNION ALL
        SELECT 'Ripperton' UNION ALL
        SELECT 'Rivas' UNION ALL
        SELECT 'Rivera' UNION ALL
        SELECT 'Roberts' UNION ALL
        SELECT 'Robinson' UNION ALL
        SELECT 'Robles' UNION ALL
        SELECT 'Rocha' UNION ALL
        SELECT 'Rodriguez' UNION ALL
        SELECT 'Rodríguez' UNION ALL
        SELECT 'Rogers' UNION ALL
        SELECT 'Rojas' UNION ALL
        SELECT 'Roland' UNION ALL
        SELECT 'Roman' UNION ALL
        SELECT 'Romero' UNION ALL
        SELECT 'Romirez' UNION ALL
        SELECT 'Romo' UNION ALL
        SELECT 'Rooney' UNION ALL
        SELECT 'Root' UNION ALL
        SELECT 'Rosales' UNION ALL
        SELECT 'Rosas' UNION ALL
        SELECT 'Rosenberg' UNION ALL
        SELECT 'Ross' UNION ALL
        SELECT 'Rossi' UNION ALL
        SELECT 'Rowland' UNION ALL
        SELECT 'Rubio' UNION ALL
        SELECT 'Rudd' UNION ALL
        SELECT 'Rude' UNION ALL
        SELECT 'Ruíz' UNION ALL
        SELECT 'Rush' UNION ALL
        SELECT 'Russell' UNION ALL
        SELECT 'Russo' UNION ALL
        SELECT 'Ruster' UNION ALL
        SELECT 'Ryan' UNION ALL
        SELECT 'Sabanthia' UNION ALL
        SELECT 'Salas' UNION ALL
        SELECT 'Salazar' UNION ALL
        SELECT 'Salcedo' UNION ALL
        SELECT 'Salgado' UNION ALL
        SELECT 'Salinas' UNION ALL
        SELECT 'Sanchez' UNION ALL
        SELECT 'Sánchez' UNION ALL
        SELECT 'Sanders' UNION ALL
        SELECT 'Sandoval' UNION ALL
        SELECT 'Sands' UNION ALL
        SELECT 'Santos' UNION ALL
        SELECT 'Sarkis' UNION ALL
        SELECT 'Sasai' UNION ALL
        SELECT 'Sasaki' UNION ALL
        SELECT 'Savage' UNION ALL
        SELECT 'Savoy' UNION ALL
        SELECT 'Saxon' UNION ALL
        SELECT 'Scardino' UNION ALL
        SELECT 'Scott' UNION ALL
        SELECT 'Seagate' UNION ALL
        SELECT 'Segura' UNION ALL
        SELECT 'Seibert' UNION ALL
        SELECT 'Sereno' UNION ALL
        SELECT 'Serrano' UNION ALL
        SELECT 'Shaver' UNION ALL
        SELECT 'Shea' UNION ALL
        SELECT 'Sheehan' UNION ALL
        SELECT 'Shields' UNION ALL
        SELECT 'Shippen' UNION ALL
        SELECT 'Shivers' UNION ALL
        SELECT 'Shock' UNION ALL
        SELECT 'Shute' UNION ALL
        SELECT 'Silva' UNION ALL
        SELECT 'Silver' UNION ALL
        SELECT 'Silverman' UNION ALL
        SELECT 'Simerly' UNION ALL
        SELECT 'Sinclair' UNION ALL
        SELECT 'Skaggs' UNION ALL
        SELECT 'Skills' UNION ALL
        SELECT 'Skinner' UNION ALL
        SELECT 'Skirth' UNION ALL
        SELECT 'Sloane' UNION ALL
        SELECT 'Small' UNION ALL
        SELECT 'Smith' UNION ALL
        SELECT 'Smoker' UNION ALL
        SELECT 'Snedeker' UNION ALL
        SELECT 'Solís' UNION ALL
        SELECT 'Soo' UNION ALL
        SELECT 'Soria' UNION ALL
        SELECT 'Sorrow' UNION ALL
        SELECT 'Sosa' UNION ALL
        SELECT 'Sotelo' UNION ALL
        SELECT 'Soto' UNION ALL
        SELECT 'Spacek' UNION ALL
        SELECT 'Spears' UNION ALL
        SELECT 'Spieth' UNION ALL
        SELECT 'Spinks' UNION ALL
        SELECT 'Stamper' UNION ALL
        SELECT 'Standifer' UNION ALL
        SELECT 'Stapleton' UNION ALL
        SELECT 'Steele' UNION ALL
        SELECT 'Stelly' UNION ALL
        SELECT 'Stewart' UNION ALL
        SELECT 'Stiner' UNION ALL
        SELECT 'Stitchen' UNION ALL
        SELECT 'Stockton' UNION ALL
        SELECT 'Stoneking' UNION ALL
        SELECT 'Story' UNION ALL
        SELECT 'Streelman' UNION ALL
        SELECT 'Strode' UNION ALL
        SELECT 'Stroud' UNION ALL
        SELECT 'Stubbings' UNION ALL
        SELECT 'Suárez' UNION ALL
        SELECT 'Suggs' UNION ALL
        SELECT 'Sullivan' UNION ALL
        SELECT 'Surrett' UNION ALL
        SELECT 'Sutton' UNION ALL
        SELECT 'Swafford' UNION ALL
        SELECT 'Sweeney' UNION ALL
        SELECT 'Swiatek' UNION ALL
        SELECT 'Swift' UNION ALL
        SELECT 'Sykes' UNION ALL
        SELECT 'Tabrizi' UNION ALL
        SELECT 'Tait' UNION ALL
        SELECT 'Tam' UNION ALL
        SELECT 'Tamlin' UNION ALL
        SELECT 'Tanaka' UNION ALL
        SELECT 'Tanner' UNION ALL
        SELECT 'Tapia' UNION ALL
        SELECT 'Tapp' UNION ALL
        SELECT 'Taylor' UNION ALL
        SELECT 'Taymor' UNION ALL
        SELECT 'Teach' UNION ALL
        SELECT 'Teague' UNION ALL
        SELECT 'Téllez' UNION ALL
        SELECT 'Temple' UNION ALL
        SELECT 'Templeton' UNION ALL
        SELECT 'Tepper' UNION ALL
        SELECT 'Terrella' UNION ALL
        SELECT 'Thain' UNION ALL
        SELECT 'Theo' UNION ALL
        SELECT 'Thomas' UNION ALL
        SELECT 'Thompson' UNION ALL
        SELECT 'Thorisdottir' UNION ALL
        SELECT 'Tillerson' UNION ALL
        SELECT 'Tippett' UNION ALL
        SELECT 'Toller' UNION ALL
        SELECT 'Tooms' UNION ALL
        SELECT 'Torres' UNION ALL
        SELECT 'Tovar' UNION ALL
        SELECT 'Tracy' UNION ALL
        SELECT 'Trainor' UNION ALL
        SELECT 'Trapp' UNION ALL
        SELECT 'Trejo' UNION ALL
        SELECT 'Trench' UNION ALL
        SELECT 'Trevino' UNION ALL
        SELECT 'Tripper' UNION ALL
        SELECT 'Trujillo' UNION ALL
        SELECT 'Trumbald' UNION ALL
        SELECT 'Trumbo' UNION ALL
        SELECT 'Truth' UNION ALL
        SELECT 'Tucker' UNION ALL
        SELECT 'Tuco' UNION ALL
        SELECT 'Turner' UNION ALL
        SELECT 'Turpin' UNION ALL
        SELECT 'Tussac' UNION ALL
        SELECT 'Tway' UNION ALL
        SELECT 'Twigg' UNION ALL
        SELECT 'Uceda' UNION ALL
        SELECT 'Udder' UNION ALL
        SELECT 'Ulett' UNION ALL
        SELECT 'Umoh' UNION ALL
        SELECT 'Underhill' UNION ALL
        SELECT 'Unger' UNION ALL
        SELECT 'Uplinger' UNION ALL
        SELECT 'Urtz' UNION ALL
        SELECT 'Uso' UNION ALL
        SELECT 'Vaccaro' UNION ALL
        SELECT 'Vader' UNION ALL
        SELECT 'Valdez' UNION ALL
        SELECT 'Valencia' UNION ALL
        SELECT 'Valenzuela' UNION ALL
        SELECT 'Vandal' UNION ALL
        SELECT 'Vargas' UNION ALL
        SELECT 'Vasher' UNION ALL
        SELECT 'Vasquez' UNION ALL
        SELECT 'Vásquez' UNION ALL
        SELECT 'Vega' UNION ALL
        SELECT 'Vegas' UNION ALL
        SELECT 'Velasco' UNION ALL
        SELECT 'Velásquez' UNION ALL
        SELECT 'Vera' UNION ALL
        SELECT 'Vess' UNION ALL
        SELECT 'Vestine' UNION ALL
        SELECT 'Vickers' UNION ALL
        SELECT 'Villa' UNION ALL
        SELECT 'Villalobos' UNION ALL
        SELECT 'Villanueva' UNION ALL
        SELECT 'Villarreal' UNION ALL
        SELECT 'Voight' UNION ALL
        SELECT 'Volek' UNION ALL
        SELECT 'Vroman' UNION ALL
        SELECT 'Wadd' UNION ALL
        SELECT 'Wagner' UNION ALL
        SELECT 'Wainright' UNION ALL
        SELECT 'Walcott' UNION ALL
        SELECT 'Walker' UNION ALL
        SELECT 'Wall' UNION ALL
        SELECT 'Wallace' UNION ALL
        SELECT 'Walsh' UNION ALL
        SELECT 'Ward' UNION ALL
        SELECT 'Warrick' UNION ALL
        SELECT 'Watson' UNION ALL
        SELECT 'Weaver' UNION ALL
        SELECT 'Webb' UNION ALL
        SELECT 'Weeks' UNION ALL
        SELECT 'Wells' UNION ALL
        SELECT 'Wexler' UNION ALL
        SELECT 'Whalen' UNION ALL
        SELECT 'Wheeler' UNION ALL
        SELECT 'Whesker' UNION ALL
        SELECT 'Whitby' UNION ALL
        SELECT 'White' UNION ALL
        SELECT 'Whitner' UNION ALL
        SELECT 'Wight' UNION ALL
        SELECT 'Wilde' UNION ALL
        SELECT 'Williams' UNION ALL
        SELECT 'Wilson' UNION ALL
        SELECT 'Winchell' UNION ALL
        SELECT 'Winchester' UNION ALL
        SELECT 'Winding' UNION ALL
        SELECT 'Winslow' UNION ALL
        SELECT 'Winters' UNION ALL
        SELECT 'Winthrop' UNION ALL
        SELECT 'Wire' UNION ALL
        SELECT 'Withers' UNION ALL
        SELECT 'Witt' UNION ALL
        SELECT 'Wixx' UNION ALL
        SELECT 'Wolf' UNION ALL
        SELECT 'Wolfenstein' UNION ALL
        SELECT 'Wolownik' UNION ALL
        SELECT 'Wong' UNION ALL
        SELECT 'Wood' UNION ALL
        SELECT 'Woodard' UNION ALL
        SELECT 'Woodland' UNION ALL
        SELECT 'Woodson' UNION ALL
        SELECT 'Woody' UNION ALL
        SELECT 'Wooster' UNION ALL
        SELECT 'Wooten' UNION ALL
        SELECT 'Wright' UNION ALL
        SELECT 'Xanders' UNION ALL
        SELECT 'Xang' UNION ALL
        SELECT 'Xavier' UNION ALL
        SELECT 'Xenakis' UNION ALL
        SELECT 'Xiang' UNION ALL
        SELECT 'Xie' UNION ALL
        SELECT 'Ximinez' UNION ALL
        SELECT 'Xu' UNION ALL
        SELECT 'Xuxa' UNION ALL
        SELECT 'Yadao' UNION ALL
        SELECT 'Yaeger' UNION ALL
        SELECT 'Yale' UNION ALL
        SELECT 'Yamaguchi' UNION ALL
        SELECT 'Yanetta' UNION ALL
        SELECT 'Yankovich' UNION ALL
        SELECT 'Yarborough' UNION ALL
        SELECT 'Yasumoto' UNION ALL
        SELECT 'Yates' UNION ALL
        SELECT 'Yearwood' UNION ALL
        SELECT 'Yellen' UNION ALL
        SELECT 'Yoakum' UNION ALL
        SELECT 'York' UNION ALL
        SELECT 'Young' UNION ALL
        SELECT 'Youngblood' UNION ALL
        SELECT 'Younger' UNION ALL
        SELECT 'Yount' UNION ALL
        SELECT 'Zabik' UNION ALL
        SELECT 'Zabinski' UNION ALL
        SELECT 'Zade' UNION ALL
        SELECT 'Zader' UNION ALL
        SELECT 'Zahn' UNION ALL
        SELECT 'Zale' UNION ALL
        SELECT 'Zamora' UNION ALL
        SELECT 'Zant' UNION ALL
        SELECT 'Zapf' UNION ALL
        SELECT 'Zappa' UNION ALL
        SELECT 'Zárate' UNION ALL
        SELECT 'Zasso' UNION ALL
        SELECT 'Zavala' UNION ALL
        SELECT 'Zavaroni' UNION ALL
        SELECT 'Zeagler' UNION ALL
        SELECT 'Zeck' UNION ALL
        SELECT 'Zedillo' UNION ALL
        SELECT 'Zeigler' UNION ALL
        SELECT 'Zeller' UNION ALL
        SELECT 'Zimmerman' UNION ALL
        SELECT 'Zipser' UNION ALL
        SELECT 'Zmich' UNION ALL
        SELECT 'Zoller' UNION ALL
        SELECT 'Zook' UNION ALL
        SELECT 'Zuckerberg' UNION ALL
        SELECT 'Zukoff' UNION ALL
        SELECT 'Zullo' UNION ALL
        SELECT 'Zúñiga'
    ) np
;
