/*creates a random first name from a list, rather than just random strings*/
CREATE OR REPLACE FUNCTION demo.first_name_generator()
AS
(
    (
    SELECT
        np.first_name
    FROM
        (
            SELECT 'Addison' AS first_name UNION ALL
            SELECT 'Adlai' UNION ALL
            SELECT 'Adrian' UNION ALL
            SELECT 'Aiden' UNION ALL
            SELECT 'Ainsley' UNION ALL
            SELECT 'Alby' UNION ALL
            SELECT 'Alex' UNION ALL
            SELECT 'Alexis' UNION ALL
            SELECT 'Ali' UNION ALL
            SELECT 'Amari' UNION ALL
            SELECT 'Amen' UNION ALL
            SELECT 'Amory' UNION ALL
            SELECT 'Andie' UNION ALL
            SELECT 'Andy' UNION ALL
            SELECT 'Angel' UNION ALL
            SELECT 'Archer' UNION ALL
            SELECT 'Arden' UNION ALL
            SELECT 'Ari' UNION ALL
            SELECT 'Ariel' UNION ALL
            SELECT 'Armani' UNION ALL
            SELECT 'Arrow' UNION ALL
            SELECT 'Arya' UNION ALL
            SELECT 'Ash' UNION ALL
            SELECT 'Ashley' UNION ALL
            SELECT 'Ashton' UNION ALL
            SELECT 'Aspen' UNION ALL
            SELECT 'Aubrey' UNION ALL
            SELECT 'Auden' UNION ALL
            SELECT 'August' UNION ALL
            SELECT 'Austin' UNION ALL
            SELECT 'Austen' UNION ALL
            SELECT 'Avery' UNION ALL
            SELECT 'Avis' UNION ALL
            SELECT 'Azariah' UNION ALL
            SELECT 'Bailey' UNION ALL
            SELECT 'Baker' UNION ALL
            SELECT 'Bay' UNION ALL
            SELECT 'Bellamy' UNION ALL
            SELECT 'Bergen' UNION ALL
            SELECT 'Bevan' UNION ALL
            SELECT 'Billy' UNION ALL
            SELECT 'Billie' UNION ALL
            SELECT 'Blaine' UNION ALL
            SELECT 'Blair' UNION ALL
            SELECT 'Blake' UNION ALL
            SELECT 'Blue' UNION ALL
            SELECT 'Bobby' UNION ALL
            SELECT 'Bowie' UNION ALL
            SELECT 'Brady' UNION ALL
            SELECT 'Brennan' UNION ALL
            SELECT 'Brent' UNION ALL
            SELECT 'Breslin' UNION ALL
            SELECT 'Brett' UNION ALL
            SELECT 'Briar' UNION ALL
            SELECT 'Brighton' UNION ALL
            SELECT 'Bronwyn' UNION ALL
            SELECT 'Brook' UNION ALL
            SELECT 'Brooke' UNION ALL
            SELECT 'Brooklyn' UNION ALL
            SELECT 'Caelan' UNION ALL
            SELECT 'Cameron' UNION ALL
            SELECT 'Campbell' UNION ALL
            SELECT 'Carmel' UNION ALL
            SELECT 'Carmen' UNION ALL
            SELECT 'Carroll' UNION ALL
            SELECT 'Carson' UNION ALL
            SELECT 'Carter' UNION ALL
            SELECT 'Karter' UNION ALL
            SELECT 'Casey' UNION ALL
            SELECT 'Cassidy' UNION ALL
            SELECT 'Celyn' UNION ALL
            SELECT 'Chandler' UNION ALL
            SELECT 'Channing' UNION ALL
            SELECT 'Charleston' UNION ALL
            SELECT 'Charlie' UNION ALL
            SELECT 'Charley' UNION ALL
            SELECT 'Chris' UNION ALL
            SELECT 'Kris' UNION ALL
            SELECT 'Christian' UNION ALL
            SELECT 'Clancy' UNION ALL
            SELECT 'Clarke' UNION ALL
            SELECT 'Clay' UNION ALL
            SELECT 'Clayton' UNION ALL
            SELECT 'Cleo' UNION ALL
            SELECT 'Cody' UNION ALL
            SELECT 'Corey' UNION ALL
            SELECT 'Cypress' UNION ALL
            SELECT 'Dakota' UNION ALL
            SELECT 'Dakotah' UNION ALL
            SELECT 'Dale' UNION ALL
            SELECT 'Dallas' UNION ALL
            SELECT 'Dana' UNION ALL
            SELECT 'Dane' UNION ALL
            SELECT 'Darby' UNION ALL
            SELECT 'Darrel' UNION ALL
            SELECT 'Darryl' UNION ALL
            SELECT 'Daryl' UNION ALL
            SELECT 'Dawson' UNION ALL
            SELECT 'Delta' UNION ALL
            SELECT 'Denver' UNION ALL
            SELECT 'Devin' UNION ALL
            SELECT 'Devon' UNION ALL
            SELECT 'Dominique' UNION ALL
            SELECT 'Dorian' UNION ALL
            SELECT 'Drew' UNION ALL
            SELECT 'Dylan' UNION ALL
            SELECT 'Easton' UNION ALL
            SELECT 'Eastyn' UNION ALL
            SELECT 'Eddie' UNION ALL
            SELECT 'Eden' UNION ALL
            SELECT 'Egypt' UNION ALL
            SELECT 'Eli' UNION ALL
            SELECT 'Ellery' UNION ALL
            SELECT 'Elliot' UNION ALL
            SELECT 'Elliott' UNION ALL
            SELECT 'Ellis' UNION ALL
            SELECT 'Ellison' UNION ALL
            SELECT 'Emerson' UNION ALL
            SELECT 'Emery' UNION ALL
            SELECT 'Emory' UNION ALL
            SELECT 'Erin' UNION ALL
            SELECT 'Ever' UNION ALL
            SELECT 'Everest' UNION ALL
            SELECT 'Fabian' UNION ALL
            SELECT 'Finley' UNION ALL
            SELECT 'Finn' UNION ALL
            SELECT 'Florian' UNION ALL
            SELECT 'Flynn' UNION ALL
            SELECT 'Francis' UNION ALL
            SELECT 'Frances' UNION ALL
            SELECT 'Frankie' UNION ALL
            SELECT 'Gabriel' UNION ALL
            SELECT 'Gene' UNION ALL
            SELECT 'Jean' UNION ALL
            SELECT 'Gentry' UNION ALL
            SELECT 'Gillian' UNION ALL
            SELECT 'Jillian' UNION ALL
            SELECT 'Glen' UNION ALL
            SELECT 'Glenn' UNION ALL
            SELECT 'Gray' UNION ALL
            SELECT 'Grey' UNION ALL
            SELECT 'Greer' UNION ALL
            SELECT 'Hadley' UNION ALL
            SELECT 'Halo' UNION ALL
            SELECT 'Hampton' UNION ALL
            SELECT 'Harley' UNION ALL
            SELECT 'Harlow' UNION ALL
            SELECT 'Harper' UNION ALL
            SELECT 'Haskell' UNION ALL
            SELECT 'Haven' UNION ALL
            SELECT 'Hayden' UNION ALL
            SELECT 'Hero' UNION ALL
            SELECT 'Holland' UNION ALL
            SELECT 'Hollis' UNION ALL
            SELECT 'Honor' UNION ALL
            SELECT 'Hudson' UNION ALL
            SELECT 'Hunter' UNION ALL
            SELECT 'Indiana' UNION ALL
            SELECT 'Indigo' UNION ALL
            SELECT 'Jackie' UNION ALL
            SELECT 'Jaqui' UNION ALL
            SELECT 'Jade' UNION ALL
            SELECT 'Jaden' UNION ALL
            SELECT 'Jaidyn' UNION ALL
            SELECT 'Jayden' UNION ALL
            SELECT 'Jael' UNION ALL
            SELECT 'James' UNION ALL
            SELECT 'Jayme' UNION ALL
            SELECT 'Jamie' UNION ALL
            SELECT 'Jan' UNION ALL
            SELECT 'Jaziah' UNION ALL
            SELECT 'Jesse' UNION ALL
            SELECT 'Jessie' UNION ALL
            SELECT 'Jody' UNION ALL
            SELECT 'Joe' UNION ALL
            SELECT 'Jordan' UNION ALL
            SELECT 'Journey' UNION ALL
            SELECT 'Jules' UNION ALL
            SELECT 'Julian' UNION ALL
            SELECT 'Justice' UNION ALL
            SELECT 'Kaden' UNION ALL
            SELECT 'Kadin' UNION ALL
            SELECT 'Kai' UNION ALL
            SELECT 'Kamryn' UNION ALL
            SELECT 'Camryn' UNION ALL
            SELECT 'Keegan' UNION ALL
            SELECT 'Keelan' UNION ALL
            SELECT 'Keely' UNION ALL
            SELECT 'Kei' UNION ALL
            SELECT 'Keith' UNION ALL
            SELECT 'Keath' UNION ALL
            SELECT 'Kelly' UNION ALL
            SELECT 'Kelsey' UNION ALL
            SELECT 'Kendall' UNION ALL
            SELECT 'Kennedy' UNION ALL
            SELECT 'Kennedi' UNION ALL
            SELECT 'Kensley' UNION ALL
            SELECT 'Kerry' UNION ALL
            SELECT 'Kevin' UNION ALL
            SELECT 'Kieran' UNION ALL
            SELECT 'Kiley' UNION ALL
            SELECT 'Kim' UNION ALL
            SELECT 'Kym' UNION ALL
            SELECT 'Kingsley' UNION ALL
            SELECT 'Kylar' UNION ALL
            SELECT 'Kyle' UNION ALL
            SELECT 'Kylin' UNION ALL
            SELECT 'Kyrie' UNION ALL
            SELECT 'Lake' UNION ALL
            SELECT 'Landry' UNION ALL
            SELECT 'Lane' UNION ALL
            SELECT 'Lee' UNION ALL
            SELECT 'Leigh' UNION ALL
            SELECT 'Lennon' UNION ALL
            SELECT 'Lennox' UNION ALL
            SELECT 'Leslie' UNION ALL
            SELECT 'Lesley' UNION ALL
            SELECT 'Lincoln' UNION ALL
            SELECT 'Linden' UNION ALL
            SELECT 'Lindsay' UNION ALL
            SELECT 'Logan' UNION ALL
            SELECT 'London' UNION ALL
            SELECT 'Lonnie' UNION ALL
            SELECT 'Loren' UNION ALL
            SELECT 'Lou' UNION ALL
            SELECT 'Lucy-Ann' UNION ALL
            SELECT 'Lucian' UNION ALL
            SELECT 'Lumi' UNION ALL
            SELECT 'Lyric' UNION ALL
            SELECT 'Macey' UNION ALL
            SELECT 'Macy' UNION ALL
            SELECT 'Mackenzie' UNION ALL
            SELECT 'Madison' UNION ALL
            SELECT 'Marley' UNION ALL
            SELECT 'Marlo' UNION ALL
            SELECT 'Marlow' UNION ALL
            SELECT 'Mason' UNION ALL
            SELECT 'Max' UNION ALL
            SELECT 'Maxwell' UNION ALL
            SELECT 'Memphis' UNION ALL
            SELECT 'Merit' UNION ALL
            SELECT 'Merritt' UNION ALL
            SELECT 'Micah' UNION ALL
            SELECT 'Michael' UNION ALL
            SELECT 'Micky' UNION ALL
            SELECT 'Milan' UNION ALL
            SELECT 'Miller' UNION ALL
            SELECT 'Monroe' UNION ALL
            SELECT 'Montana' UNION ALL
            SELECT 'Morgan' UNION ALL
            SELECT 'Moriah' UNION ALL
            SELECT 'Murphy' UNION ALL
            SELECT 'Navy' UNION ALL
            SELECT 'Nevada' UNION ALL
            SELECT 'Nicky' UNION ALL
            SELECT 'Nico' UNION ALL
            SELECT 'Nikita' UNION ALL
            SELECT 'Noel' UNION ALL
            SELECT 'Noelle' UNION ALL
            SELECT 'Oakley' UNION ALL
            SELECT 'Ocean' UNION ALL
            SELECT 'Ode' UNION ALL
            SELECT 'Ore' UNION ALL
            SELECT 'Oswin' UNION ALL
            SELECT 'Owen' UNION ALL
            SELECT 'Paris' UNION ALL
            SELECT 'Parker' UNION ALL
            SELECT 'Pat' UNION ALL
            SELECT 'Payson' UNION ALL
            SELECT 'Payton' UNION ALL
            SELECT 'Peyton' UNION ALL
            SELECT 'Peace' UNION ALL
            SELECT 'Perry' UNION ALL
            SELECT 'Perrie' UNION ALL
            SELECT 'Phoenix' UNION ALL
            SELECT 'Piper' UNION ALL
            SELECT 'Poet' UNION ALL
            SELECT 'Quincy' UNION ALL
            SELECT 'Quinn' UNION ALL
            SELECT 'Raleigh' UNION ALL
            SELECT 'Ramsey' UNION ALL
            SELECT 'Raphael' UNION ALL
            SELECT 'Ray' UNION ALL
            SELECT 'Rayne' UNION ALL
            SELECT 'Rain' UNION ALL
            SELECT 'Reagan' UNION ALL
            SELECT 'Rebel' UNION ALL
            SELECT 'Reed' UNION ALL
            SELECT 'Reese' UNION ALL
            SELECT 'Regan' UNION ALL
            SELECT 'Reilly' UNION ALL
            SELECT 'Remi' UNION ALL
            SELECT 'Remington' UNION ALL
            SELECT 'Remy' UNION ALL
            SELECT 'Rene' UNION ALL
            SELECT 'Renee' UNION ALL
            SELECT 'Revel' UNION ALL
            SELECT 'Ridley' UNION ALL
            SELECT 'Riley' UNION ALL
            SELECT 'Ryley' UNION ALL
            SELECT 'Rio' UNION ALL
            SELECT 'Ripley' UNION ALL
            SELECT 'River' UNION ALL
            SELECT 'Roan' UNION ALL
            SELECT 'Robin' UNION ALL
            SELECT 'Robyn' UNION ALL
            SELECT 'Rorey' UNION ALL
            SELECT 'Rory' UNION ALL
            SELECT 'Roux' UNION ALL
            SELECT 'Rowan' UNION ALL
            SELECT 'Royal' UNION ALL
            SELECT 'Rudy' UNION ALL
            SELECT 'Rumi' UNION ALL
            SELECT 'Ryan' UNION ALL
            SELECT 'Rylan' UNION ALL
            SELECT 'Sage' UNION ALL
            SELECT 'Sailor' UNION ALL
            SELECT 'Salem' UNION ALL
            SELECT 'Sam' UNION ALL
            SELECT 'Samar' UNION ALL
            SELECT 'Sasha' UNION ALL
            SELECT 'Sawyer' UNION ALL
            SELECT 'Scout' UNION ALL
            SELECT 'Sean' UNION ALL
            SELECT 'Seneca' UNION ALL
            SELECT 'Shae' UNION ALL
            SELECT 'Shannon' UNION ALL
            SELECT 'Shawn' UNION ALL
            SELECT 'Shay' UNION ALL
            SELECT 'Shiloh' UNION ALL
            SELECT 'Sidney' UNION ALL
            SELECT 'Sky' UNION ALL
            SELECT 'Skye' UNION ALL
            SELECT 'Skyler' UNION ALL
            SELECT 'Skylar' UNION ALL
            SELECT 'Sloan' UNION ALL
            SELECT 'Slone' UNION ALL
            SELECT 'Spencer' UNION ALL
            SELECT 'Sterling' UNION ALL
            SELECT 'Stirling' UNION ALL
            SELECT 'Stevie' UNION ALL
            SELECT 'Storm' UNION ALL
            SELECT 'Sunny' UNION ALL
            SELECT 'Sutton' UNION ALL
            SELECT 'Sydney' UNION ALL
            SELECT 'Tanner' UNION ALL
            SELECT 'Tate' UNION ALL
            SELECT 'Tatum' UNION ALL
            SELECT 'Taylen' UNION ALL
            SELECT 'Taylor' UNION ALL
            SELECT 'Tennessee' UNION ALL
            SELECT 'Tennyson' UNION ALL
            SELECT 'Teri' UNION ALL
            SELECT 'Terry' UNION ALL
            SELECT 'Texas' UNION ALL
            SELECT 'Timber' UNION ALL
            SELECT 'Tobin' UNION ALL
            SELECT 'Toby' UNION ALL
            SELECT 'Tobey' UNION ALL
            SELECT 'Tony' UNION ALL
            SELECT 'Toni' UNION ALL
            SELECT 'Tory' UNION ALL
            SELECT 'Tori' UNION ALL
            SELECT 'Tracy' UNION ALL
            SELECT 'Trinity' UNION ALL
            SELECT 'Tristan' UNION ALL
            SELECT 'Tru' UNION ALL
            SELECT 'Tyler' UNION ALL
            SELECT 'Umber' UNION ALL
            SELECT 'Unique' UNION ALL
            SELECT 'Val' UNION ALL
            SELECT 'Valentine' UNION ALL
            SELECT 'Vesper' UNION ALL
            SELECT 'Vick' UNION ALL
            SELECT 'Wallis' UNION ALL
            SELECT 'Wallace' UNION ALL
            SELECT 'Wesley' UNION ALL
            SELECT 'West' UNION ALL
            SELECT 'Whitney' UNION ALL
            SELECT 'Wilder' UNION ALL
            SELECT 'Winn' UNION ALL
            SELECT 'Wynn' UNION ALL
            SELECT 'Winter' UNION ALL
            SELECT 'Wisdom' UNION ALL
            SELECT 'Wren' UNION ALL
            SELECT 'Wyatt' UNION ALL
            SELECT 'Wynne' UNION ALL
            SELECT 'Xen' UNION ALL
            SELECT 'Xoan' UNION ALL
            SELECT 'Yael' UNION ALL
            SELECT 'Zephyr' UNION ALL
            SELECT 'Zion' UNION ALL
            SELECT 'Terry' UNION ALL
            SELECT 'Jamie' UNION ALL
            SELECT 'Francis' UNION ALL
            SELECT 'Kris' UNION ALL
            SELECT 'Charlie' UNION ALL
            SELECT 'Emerson' UNION ALL
            SELECT 'River' UNION ALL
            SELECT 'Tatum' UNION ALL
            SELECT 'Avery' UNION ALL
            SELECT 'Brooklyn' UNION ALL
            SELECT 'Campbell' UNION ALL
            SELECT 'Gray' UNION ALL
            SELECT 'Jordan' UNION ALL
            SELECT 'Morgan' UNION ALL
            SELECT 'Peyton' UNION ALL
            SELECT 'Reese' UNION ALL
            SELECT 'Riley' UNION ALL
            SELECT 'Robin' UNION ALL
            SELECT 'Rory' UNION ALL
            SELECT 'Sawyer' UNION ALL
            SELECT 'Sutton' UNION ALL
            SELECT 'Dakota' UNION ALL
            SELECT 'Parker' UNION ALL
            SELECT 'Quinn' UNION ALL
            SELECT 'Phoenix' UNION ALL
            SELECT 'Kendall' UNION ALL
            SELECT 'Harley' UNION ALL
            SELECT 'Blake' UNION ALL
            SELECT 'Hayden' UNION ALL
            SELECT 'Elliott' UNION ALL
            SELECT 'Karter' UNION ALL
            SELECT 'Taylor' UNION ALL
            SELECT 'Angel'
        ) np
        ORDER BY
            rand()
        LIMIT 1
    )
)
