/*picks a random iso language code--list is accurate as of 2026*/
CREATE OR REPLACE FUNCTION dpa.random_language_code()
as
(
    (
        SELECT
            np.language_code
        FROM
            (
                    SELECT 'aar' AS language_code UNION ALL
                    SELECT 'abk' UNION ALL
                    SELECT 'ace' UNION ALL
                    SELECT 'ach' UNION ALL
                    SELECT 'ada' UNION ALL
                    SELECT 'ady' UNION ALL
                    SELECT 'afa' UNION ALL
                    SELECT 'afh' UNION ALL
                    SELECT 'afr' UNION ALL
                    SELECT 'ain' UNION ALL
                    SELECT 'aka' UNION ALL
                    SELECT 'akk' UNION ALL
                    SELECT 'alb' UNION ALL
                    SELECT 'ale' UNION ALL
                    SELECT 'alg' UNION ALL
                    SELECT 'alt' UNION ALL
                    SELECT 'amh' UNION ALL
                    SELECT 'ang' UNION ALL
                    SELECT 'anp' UNION ALL
                    SELECT 'apa' UNION ALL
                    SELECT 'ara' UNION ALL
                    SELECT 'arc' UNION ALL
                    SELECT 'arg' UNION ALL
                    SELECT 'arm' UNION ALL
                    SELECT 'arn' UNION ALL
                    SELECT 'arp' UNION ALL
                    SELECT 'art' UNION ALL
                    SELECT 'arw' UNION ALL
                    SELECT 'asm' UNION ALL
                    SELECT 'ast' UNION ALL
                    SELECT 'ath' UNION ALL
                    SELECT 'aus' UNION ALL
                    SELECT 'ava' UNION ALL
                    SELECT 'ave' UNION ALL
                    SELECT 'awa' UNION ALL
                    SELECT 'aym' UNION ALL
                    SELECT 'aze' UNION ALL
                    SELECT 'bad' UNION ALL
                    SELECT 'bai' UNION ALL
                    SELECT 'bak' UNION ALL
                    SELECT 'bal' UNION ALL
                    SELECT 'bam' UNION ALL
                    SELECT 'ban' UNION ALL
                    SELECT 'baq' UNION ALL
                    SELECT 'bas' UNION ALL
                    SELECT 'bat' UNION ALL
                    SELECT 'bej' UNION ALL
                    SELECT 'bel' UNION ALL
                    SELECT 'bem' UNION ALL
                    SELECT 'ben' UNION ALL
                    SELECT 'ber' UNION ALL
                    SELECT 'bho' UNION ALL
                    SELECT 'bih' UNION ALL
                    SELECT 'bik' UNION ALL
                    SELECT 'bin' UNION ALL
                    SELECT 'bis' UNION ALL
                    SELECT 'bla' UNION ALL
                    SELECT 'bnt' UNION ALL
                    SELECT 'bod' UNION ALL
                    SELECT 'bos' UNION ALL
                    SELECT 'bra' UNION ALL
                    SELECT 'bre' UNION ALL
                    SELECT 'btk' UNION ALL
                    SELECT 'bua' UNION ALL
                    SELECT 'bug' UNION ALL
                    SELECT 'bul' UNION ALL
                    SELECT 'bur' UNION ALL
                    SELECT 'byn' UNION ALL
                    SELECT 'cad' UNION ALL
                    SELECT 'cai' UNION ALL
                    SELECT 'car' UNION ALL
                    SELECT 'cat' UNION ALL
                    SELECT 'cau' UNION ALL
                    SELECT 'ceb' UNION ALL
                    SELECT 'cel' UNION ALL
                    SELECT 'ces' UNION ALL
                    SELECT 'cha' UNION ALL
                    SELECT 'chb' UNION ALL
                    SELECT 'che' UNION ALL
                    SELECT 'chg' UNION ALL
                    SELECT 'chi' UNION ALL
                    SELECT 'chk' UNION ALL
                    SELECT 'chm' UNION ALL
                    SELECT 'chn' UNION ALL
                    SELECT 'cho' UNION ALL
                    SELECT 'chp' UNION ALL
                    SELECT 'chr' UNION ALL
                    SELECT 'chu' UNION ALL
                    SELECT 'chv' UNION ALL
                    SELECT 'chy' UNION ALL
                    SELECT 'cmc' UNION ALL
                    SELECT 'cnr' UNION ALL
                    SELECT 'cop' UNION ALL
                    SELECT 'cor' UNION ALL
                    SELECT 'cos' UNION ALL
                    SELECT 'cpe' UNION ALL
                    SELECT 'cpf' UNION ALL
                    SELECT 'cpp' UNION ALL
                    SELECT 'cre' UNION ALL
                    SELECT 'crh' UNION ALL
                    SELECT 'crp' UNION ALL
                    SELECT 'csb' UNION ALL
                    SELECT 'cus' UNION ALL
                    SELECT 'cym' UNION ALL
                    SELECT 'cze' UNION ALL
                    SELECT 'dak' UNION ALL
                    SELECT 'dan' UNION ALL
                    SELECT 'dar' UNION ALL
                    SELECT 'day' UNION ALL
                    SELECT 'del' UNION ALL
                    SELECT 'den' UNION ALL
                    SELECT 'deu' UNION ALL
                    SELECT 'dgr' UNION ALL
                    SELECT 'din' UNION ALL
                    SELECT 'div' UNION ALL
                    SELECT 'doi' UNION ALL
                    SELECT 'dra' UNION ALL
                    SELECT 'dsb' UNION ALL
                    SELECT 'dua' UNION ALL
                    SELECT 'dum' UNION ALL
                    SELECT 'dut' UNION ALL
                    SELECT 'dyu' UNION ALL
                    SELECT 'dzo' UNION ALL
                    SELECT 'efi' UNION ALL
                    SELECT 'egy' UNION ALL
                    SELECT 'eka' UNION ALL
                    SELECT 'ell' UNION ALL
                    SELECT 'elx' UNION ALL
                    SELECT 'eng' UNION ALL
                    SELECT 'enm' UNION ALL
                    SELECT 'epo' UNION ALL
                    SELECT 'est' UNION ALL
                    SELECT 'eus' UNION ALL
                    SELECT 'ewe' UNION ALL
                    SELECT 'ewo' UNION ALL
                    SELECT 'fan' UNION ALL
                    SELECT 'fao' UNION ALL
                    SELECT 'fas' UNION ALL
                    SELECT 'fat' UNION ALL
                    SELECT 'fij' UNION ALL
                    SELECT 'fil' UNION ALL
                    SELECT 'fin' UNION ALL
                    SELECT 'fiu' UNION ALL
                    SELECT 'fon' UNION ALL
                    SELECT 'fra' UNION ALL
                    SELECT 'fre' UNION ALL
                    SELECT 'frm' UNION ALL
                    SELECT 'fro' UNION ALL
                    SELECT 'frr' UNION ALL
                    SELECT 'frs' UNION ALL
                    SELECT 'fry' UNION ALL
                    SELECT 'ful' UNION ALL
                    SELECT 'fur' UNION ALL
                    SELECT 'gaa' UNION ALL
                    SELECT 'gay' UNION ALL
                    SELECT 'gba' UNION ALL
                    SELECT 'gem' UNION ALL
                    SELECT 'geo' UNION ALL
                    SELECT 'ger' UNION ALL
                    SELECT 'gez' UNION ALL
                    SELECT 'gil' UNION ALL
                    SELECT 'gla' UNION ALL
                    SELECT 'gle' UNION ALL
                    SELECT 'glg' UNION ALL
                    SELECT 'glv' UNION ALL
                    SELECT 'gmh' UNION ALL
                    SELECT 'goh' UNION ALL
                    SELECT 'gon' UNION ALL
                    SELECT 'gor' UNION ALL
                    SELECT 'got' UNION ALL
                    SELECT 'grb' UNION ALL
                    SELECT 'grc' UNION ALL
                    SELECT 'gre' UNION ALL
                    SELECT 'grn' UNION ALL
                    SELECT 'gsw' UNION ALL
                    SELECT 'guj' UNION ALL
                    SELECT 'gwi' UNION ALL
                    SELECT 'hai' UNION ALL
                    SELECT 'hat' UNION ALL
                    SELECT 'hau' UNION ALL
                    SELECT 'haw' UNION ALL
                    SELECT 'heb' UNION ALL
                    SELECT 'her' UNION ALL
                    SELECT 'hil' UNION ALL
                    SELECT 'him' UNION ALL
                    SELECT 'hin' UNION ALL
                    SELECT 'hit' UNION ALL
                    SELECT 'hmn' UNION ALL
                    SELECT 'hmo' UNION ALL
                    SELECT 'hrv' UNION ALL
                    SELECT 'hsb' UNION ALL
                    SELECT 'hun' UNION ALL
                    SELECT 'hup' UNION ALL
                    SELECT 'hye' UNION ALL
                    SELECT 'iba' UNION ALL
                    SELECT 'ibo' UNION ALL
                    SELECT 'ice' UNION ALL
                    SELECT 'ido' UNION ALL
                    SELECT 'iii' UNION ALL
                    SELECT 'ijo' UNION ALL
                    SELECT 'iku' UNION ALL
                    SELECT 'ile' UNION ALL
                    SELECT 'ilo' UNION ALL
                    SELECT 'ina' UNION ALL
                    SELECT 'inc' UNION ALL
                    SELECT 'ind' UNION ALL
                    SELECT 'ine' UNION ALL
                    SELECT 'inh' UNION ALL
                    SELECT 'ipk' UNION ALL
                    SELECT 'ira' UNION ALL
                    SELECT 'iro' UNION ALL
                    SELECT 'isl' UNION ALL
                    SELECT 'ita' UNION ALL
                    SELECT 'jav' UNION ALL
                    SELECT 'jbo' UNION ALL
                    SELECT 'jpn' UNION ALL
                    SELECT 'jpr' UNION ALL
                    SELECT 'jrb' UNION ALL
                    SELECT 'kaa' UNION ALL
                    SELECT 'kab' UNION ALL
                    SELECT 'kac' UNION ALL
                    SELECT 'kal' UNION ALL
                    SELECT 'kam' UNION ALL
                    SELECT 'kan' UNION ALL
                    SELECT 'kar' UNION ALL
                    SELECT 'kas' UNION ALL
                    SELECT 'kat' UNION ALL
                    SELECT 'kau' UNION ALL
                    SELECT 'kaw' UNION ALL
                    SELECT 'kaz' UNION ALL
                    SELECT 'kbd' UNION ALL
                    SELECT 'kha' UNION ALL
                    SELECT 'khi' UNION ALL
                    SELECT 'khm' UNION ALL
                    SELECT 'kho' UNION ALL
                    SELECT 'kik' UNION ALL
                    SELECT 'kin' UNION ALL
                    SELECT 'kir' UNION ALL
                    SELECT 'kmb' UNION ALL
                    SELECT 'kok' UNION ALL
                    SELECT 'kom' UNION ALL
                    SELECT 'kon' UNION ALL
                    SELECT 'kor' UNION ALL
                    SELECT 'kos' UNION ALL
                    SELECT 'kpe' UNION ALL
                    SELECT 'krc' UNION ALL
                    SELECT 'krl' UNION ALL
                    SELECT 'kro' UNION ALL
                    SELECT 'kru' UNION ALL
                    SELECT 'kua' UNION ALL
                    SELECT 'kum' UNION ALL
                    SELECT 'kur' UNION ALL
                    SELECT 'kut' UNION ALL
                    SELECT 'lad' UNION ALL
                    SELECT 'lah' UNION ALL
                    SELECT 'lam' UNION ALL
                    SELECT 'lao' UNION ALL
                    SELECT 'lat' UNION ALL
                    SELECT 'lav' UNION ALL
                    SELECT 'lez' UNION ALL
                    SELECT 'lim' UNION ALL
                    SELECT 'lin' UNION ALL
                    SELECT 'lit' UNION ALL
                    SELECT 'lol' UNION ALL
                    SELECT 'loz' UNION ALL
                    SELECT 'ltz' UNION ALL
                    SELECT 'lua' UNION ALL
                    SELECT 'lub' UNION ALL
                    SELECT 'lug' UNION ALL
                    SELECT 'lui' UNION ALL
                    SELECT 'lun' UNION ALL
                    SELECT 'luo' UNION ALL
                    SELECT 'lus' UNION ALL
                    SELECT 'mac' UNION ALL
                    SELECT 'mad' UNION ALL
                    SELECT 'mag' UNION ALL
                    SELECT 'mah' UNION ALL
                    SELECT 'mai' UNION ALL
                    SELECT 'mak' UNION ALL
                    SELECT 'mal' UNION ALL
                    SELECT 'man' UNION ALL
                    SELECT 'mao' UNION ALL
                    SELECT 'map' UNION ALL
                    SELECT 'mar' UNION ALL
                    SELECT 'mas' UNION ALL
                    SELECT 'may' UNION ALL
                    SELECT 'mdf' UNION ALL
                    SELECT 'mdr' UNION ALL
                    SELECT 'men' UNION ALL
                    SELECT 'mga' UNION ALL
                    SELECT 'mic' UNION ALL
                    SELECT 'min' UNION ALL
                    SELECT 'mis' UNION ALL
                    SELECT 'mkd' UNION ALL
                    SELECT 'mkh' UNION ALL
                    SELECT 'mlg' UNION ALL
                    SELECT 'mlt' UNION ALL
                    SELECT 'mnc' UNION ALL
                    SELECT 'mni' UNION ALL
                    SELECT 'mno' UNION ALL
                    SELECT 'moh' UNION ALL
                    SELECT 'mon' UNION ALL
                    SELECT 'mos' UNION ALL
                    SELECT 'mri' UNION ALL
                    SELECT 'msa' UNION ALL
                    SELECT 'mul' UNION ALL
                    SELECT 'mun' UNION ALL
                    SELECT 'mus' UNION ALL
                    SELECT 'mwl' UNION ALL
                    SELECT 'mwr' UNION ALL
                    SELECT 'mya' UNION ALL
                    SELECT 'myn' UNION ALL
                    SELECT 'myv' UNION ALL
                    SELECT 'nah' UNION ALL
                    SELECT 'nai' UNION ALL
                    SELECT 'nap' UNION ALL
                    SELECT 'nau' UNION ALL
                    SELECT 'nav' UNION ALL
                    SELECT 'nbl' UNION ALL
                    SELECT 'nde' UNION ALL
                    SELECT 'ndo' UNION ALL
                    SELECT 'nds' UNION ALL
                    SELECT 'nep' UNION ALL
                    SELECT 'new' UNION ALL
                    SELECT 'nia' UNION ALL
                    SELECT 'nic' UNION ALL
                    SELECT 'nid' UNION ALL
                    SELECT 'niu' UNION ALL
                    SELECT 'nld' UNION ALL
                    SELECT 'nno' UNION ALL
                    SELECT 'nob' UNION ALL
                    SELECT 'nog' UNION ALL
                    SELECT 'non' UNION ALL
                    SELECT 'nor' UNION ALL
                    SELECT 'nqo' UNION ALL
                    SELECT 'nso' UNION ALL
                    SELECT 'nub' UNION ALL
                    SELECT 'nwc' UNION ALL
                    SELECT 'nya' UNION ALL
                    SELECT 'nym' UNION ALL
                    SELECT 'nyn' UNION ALL
                    SELECT 'nyo' UNION ALL
                    SELECT 'nzi' UNION ALL
                    SELECT 'oci' UNION ALL
                    SELECT 'oji' UNION ALL
                    SELECT 'ori' UNION ALL
                    SELECT 'orm' UNION ALL
                    SELECT 'osa' UNION ALL
                    SELECT 'oss' UNION ALL
                    SELECT 'ota' UNION ALL
                    SELECT 'oto' UNION ALL
                    SELECT 'paa' UNION ALL
                    SELECT 'pag' UNION ALL
                    SELECT 'pal' UNION ALL
                    SELECT 'pam' UNION ALL
                    SELECT 'pan' UNION ALL
                    SELECT 'pap' UNION ALL
                    SELECT 'pau' UNION ALL
                    SELECT 'peo' UNION ALL
                    SELECT 'per' UNION ALL
                    SELECT 'phi' UNION ALL
                    SELECT 'phn' UNION ALL
                    SELECT 'pli' UNION ALL
                    SELECT 'pol' UNION ALL
                    SELECT 'pon' UNION ALL
                    SELECT 'por' UNION ALL
                    SELECT 'pra' UNION ALL
                    SELECT 'pro' UNION ALL
                    SELECT 'pus' UNION ALL
                    SELECT 'qaa' UNION ALL
                    SELECT 'qtz' UNION ALL
                    SELECT 'que' UNION ALL
                    SELECT 'raj' UNION ALL
                    SELECT 'rap' UNION ALL
                    SELECT 'rar' UNION ALL
                    SELECT 'roa' UNION ALL
                    SELECT 'roh' UNION ALL
                    SELECT 'rom' UNION ALL
                    SELECT 'ron' UNION ALL
                    SELECT 'rum' UNION ALL
                    SELECT 'run' UNION ALL
                    SELECT 'rup' UNION ALL
                    SELECT 'rus' UNION ALL
                    SELECT 'sad' UNION ALL
                    SELECT 'sag' UNION ALL
                    SELECT 'sah' UNION ALL
                    SELECT 'sai' UNION ALL
                    SELECT 'sal' UNION ALL
                    SELECT 'sam' UNION ALL
                    SELECT 'san' UNION ALL
                    SELECT 'sas' UNION ALL
                    SELECT 'sat' UNION ALL
                    SELECT 'scn' UNION ALL
                    SELECT 'sco' UNION ALL
                    SELECT 'sel' UNION ALL
                    SELECT 'sem' UNION ALL
                    SELECT 'sga' UNION ALL
                    SELECT 'sgn' UNION ALL
                    SELECT 'shn' UNION ALL
                    SELECT 'sid' UNION ALL
                    SELECT 'sin' UNION ALL
                    SELECT 'sio' UNION ALL
                    SELECT 'sit' UNION ALL
                    SELECT 'sla' UNION ALL
                    SELECT 'slk' UNION ALL
                    SELECT 'slo' UNION ALL
                    SELECT 'slv' UNION ALL
                    SELECT 'sma' UNION ALL
                    SELECT 'sme' UNION ALL
                    SELECT 'smi' UNION ALL
                    SELECT 'smj' UNION ALL
                    SELECT 'smn' UNION ALL
                    SELECT 'smo' UNION ALL
                    SELECT 'sms' UNION ALL
                    SELECT 'sna' UNION ALL
                    SELECT 'snd' UNION ALL
                    SELECT 'snk' UNION ALL
                    SELECT 'sog' UNION ALL
                    SELECT 'som' UNION ALL
                    SELECT 'son' UNION ALL
                    SELECT 'sot' UNION ALL
                    SELECT 'spa' UNION ALL
                    SELECT 'sqi' UNION ALL
                    SELECT 'srd' UNION ALL
                    SELECT 'srn' UNION ALL
                    SELECT 'srp' UNION ALL
                    SELECT 'srr' UNION ALL
                    SELECT 'ssa' UNION ALL
                    SELECT 'ssw' UNION ALL
                    SELECT 'suk' UNION ALL
                    SELECT 'sun' UNION ALL
                    SELECT 'sus' UNION ALL
                    SELECT 'sux' UNION ALL
                    SELECT 'swa' UNION ALL
                    SELECT 'swe' UNION ALL
                    SELECT 'syc' UNION ALL
                    SELECT 'syr' UNION ALL
                    SELECT 'tah' UNION ALL
                    SELECT 'tai' UNION ALL
                    SELECT 'tam' UNION ALL
                    SELECT 'tat' UNION ALL
                    SELECT 'tel' UNION ALL
                    SELECT 'tem' UNION ALL
                    SELECT 'ter' UNION ALL
                    SELECT 'tet' UNION ALL
                    SELECT 'tgk' UNION ALL
                    SELECT 'tgl' UNION ALL
                    SELECT 'tha' UNION ALL
                    SELECT 'tib' UNION ALL
                    SELECT 'tig' UNION ALL
                    SELECT 'tir' UNION ALL
                    SELECT 'tiv' UNION ALL
                    SELECT 'tkl' UNION ALL
                    SELECT 'tlh' UNION ALL
                    SELECT 'tli' UNION ALL
                    SELECT 'tmh' UNION ALL
                    SELECT 'tog' UNION ALL
                    SELECT 'ton' UNION ALL
                    SELECT 'tpi' UNION ALL
                    SELECT 'tsi' UNION ALL
                    SELECT 'tsn' UNION ALL
                    SELECT 'tso' UNION ALL
                    SELECT 'tuk' UNION ALL
                    SELECT 'tum' UNION ALL
                    SELECT 'tup' UNION ALL
                    SELECT 'tur' UNION ALL
                    SELECT 'tut' UNION ALL
                    SELECT 'tvl' UNION ALL
                    SELECT 'twi' UNION ALL
                    SELECT 'tyv' UNION ALL
                    SELECT 'udm' UNION ALL
                    SELECT 'uga' UNION ALL
                    SELECT 'uig' UNION ALL
                    SELECT 'ukr' UNION ALL
                    SELECT 'umb' UNION ALL
                    SELECT 'und' UNION ALL
                    SELECT 'urd' UNION ALL
                    SELECT 'uzb' UNION ALL
                    SELECT 'vai' UNION ALL
                    SELECT 'ven' UNION ALL
                    SELECT 'vie' UNION ALL
                    SELECT 'vol' UNION ALL
                    SELECT 'vot' UNION ALL
                    SELECT 'wak' UNION ALL
                    SELECT 'wal' UNION ALL
                    SELECT 'war' UNION ALL
                    SELECT 'was' UNION ALL
                    SELECT 'wel' UNION ALL
                    SELECT 'wen' UNION ALL
                    SELECT 'wln' UNION ALL
                    SELECT 'wol' UNION ALL
                    SELECT 'xal' UNION ALL
                    SELECT 'xho' UNION ALL
                    SELECT 'yao' UNION ALL
                    SELECT 'yap' UNION ALL
                    SELECT 'yid' UNION ALL
                    SELECT 'yor' UNION ALL
                    SELECT 'ypk' UNION ALL
                    SELECT 'zap' UNION ALL
                    SELECT 'zbl' UNION ALL
                    SELECT 'zen' UNION ALL
                    SELECT 'zgh' UNION ALL
                    SELECT 'zha' UNION ALL
                    SELECT 'zho' UNION ALL
                    SELECT 'znd' UNION ALL
                    SELECT 'zul' UNION ALL
                    SELECT 'zun' UNION ALL
                    SELECT 'zxx' UNION ALL
                    SELECT 'zza'
            ) np
            ORDER BY RAND()
            LIMIT 1
    )
)
