/*picks a random area code from a list--list is accurate as of 2026*/
CREATE OR REPLACE FUNCTION dpa.random_area_code()
as
(
    (
        SELECT
            np.area_code
        FROM
            (
                SELECT '201' AS area_code UNION ALL
                SELECT '202' UNION ALL
                SELECT '203' UNION ALL
                SELECT '204' UNION ALL
                SELECT '205' UNION ALL
                SELECT '206' UNION ALL
                SELECT '207' UNION ALL
                SELECT '208' UNION ALL
                SELECT '209' UNION ALL
                SELECT '210' UNION ALL
                SELECT '211' UNION ALL
                SELECT '212' UNION ALL
                SELECT '213' UNION ALL
                SELECT '214' UNION ALL
                SELECT '215' UNION ALL
                SELECT '216' UNION ALL
                SELECT '217' UNION ALL
                SELECT '218' UNION ALL
                SELECT '219' UNION ALL
                SELECT '224' UNION ALL
                SELECT '225' UNION ALL
                SELECT '228' UNION ALL
                SELECT '229' UNION ALL
                SELECT '231' UNION ALL
                SELECT '234' UNION ALL
                SELECT '236' UNION ALL
                SELECT '239' UNION ALL
                SELECT '240' UNION ALL
                SELECT '242' UNION ALL
                SELECT '246' UNION ALL
                SELECT '248' UNION ALL
                SELECT '249' UNION ALL
                SELECT '250' UNION ALL
                SELECT '251' UNION ALL
                SELECT '252' UNION ALL
                SELECT '253' UNION ALL
                SELECT '254' UNION ALL
                SELECT '256' UNION ALL
                SELECT '260' UNION ALL
                SELECT '262' UNION ALL
                SELECT '264' UNION ALL
                SELECT '267' UNION ALL
                SELECT '268' UNION ALL
                SELECT '269' UNION ALL
                SELECT '270' UNION ALL
                SELECT '276' UNION ALL
                SELECT '278' UNION ALL
                SELECT '280' UNION ALL
                SELECT '281' UNION ALL
                SELECT '282' UNION ALL
                SELECT '283' UNION ALL
                SELECT '284' UNION ALL
                SELECT '289' UNION ALL
                SELECT '301' UNION ALL
                SELECT '302' UNION ALL
                SELECT '303' UNION ALL
                SELECT '304' UNION ALL
                SELECT '305' UNION ALL
                SELECT '306' UNION ALL
                SELECT '307' UNION ALL
                SELECT '308' UNION ALL
                SELECT '309' UNION ALL
                SELECT '310' UNION ALL
                SELECT '311' UNION ALL
                SELECT '312' UNION ALL
                SELECT '313' UNION ALL
                SELECT '314' UNION ALL
                SELECT '315' UNION ALL
                SELECT '316' UNION ALL
                SELECT '317' UNION ALL
                SELECT '318' UNION ALL
                SELECT '319' UNION ALL
                SELECT '320' UNION ALL
                SELECT '321' UNION ALL
                SELECT '323' UNION ALL
                SELECT '325' UNION ALL
                SELECT '327' UNION ALL
                SELECT '330' UNION ALL
                SELECT '331' UNION ALL
                SELECT '334' UNION ALL
                SELECT '336' UNION ALL
                SELECT '337' UNION ALL
                SELECT '339' UNION ALL
                SELECT '340' UNION ALL
                SELECT '341' UNION ALL
                SELECT '345' UNION ALL
                SELECT '347' UNION ALL
                SELECT '351' UNION ALL
                SELECT '352' UNION ALL
                SELECT '353' UNION ALL
                SELECT '354' UNION ALL
                SELECT '358' UNION ALL
                SELECT '360' UNION ALL
                SELECT '361' UNION ALL
                SELECT '369' UNION ALL
                SELECT '380' UNION ALL
                SELECT '381' UNION ALL
                SELECT '383' UNION ALL
                SELECT '385' UNION ALL
                SELECT '386' UNION ALL
                SELECT '401' UNION ALL
                SELECT '402' UNION ALL
                SELECT '403' UNION ALL
                SELECT '404' UNION ALL
                SELECT '405' UNION ALL
                SELECT '406' UNION ALL
                SELECT '407' UNION ALL
                SELECT '408' UNION ALL
                SELECT '409' UNION ALL
                SELECT '410' UNION ALL
                SELECT '411' UNION ALL
                SELECT '412' UNION ALL
                SELECT '413' UNION ALL
                SELECT '414' UNION ALL
                SELECT '415' UNION ALL
                SELECT '416' UNION ALL
                SELECT '417' UNION ALL
                SELECT '418' UNION ALL
                SELECT '419' UNION ALL
                SELECT '420' UNION ALL
                SELECT '423' UNION ALL
                SELECT '424' UNION ALL
                SELECT '425' UNION ALL
                SELECT '430' UNION ALL
                SELECT '432' UNION ALL
                SELECT '434' UNION ALL
                SELECT '435' UNION ALL
                SELECT '438' UNION ALL
                SELECT '440' UNION ALL
                SELECT '441' UNION ALL
                SELECT '442' UNION ALL
                SELECT '443' UNION ALL
                SELECT '445' UNION ALL
                SELECT '450' UNION ALL
                SELECT '456' UNION ALL
                SELECT '464' UNION ALL
                SELECT '469' UNION ALL
                SELECT '470' UNION ALL
                SELECT '473' UNION ALL
                SELECT '475' UNION ALL
                SELECT '478' UNION ALL
                SELECT '479' UNION ALL
                SELECT '480' UNION ALL
                SELECT '484' UNION ALL
                SELECT '500' UNION ALL
                SELECT '501' UNION ALL
                SELECT '502' UNION ALL
                SELECT '503' UNION ALL
                SELECT '504' UNION ALL
                SELECT '505' UNION ALL
                SELECT '506' UNION ALL
                SELECT '507' UNION ALL
                SELECT '508' UNION ALL
                SELECT '509' UNION ALL
                SELECT '510' UNION ALL
                SELECT '511' UNION ALL
                SELECT '512' UNION ALL
                SELECT '513' UNION ALL
                SELECT '514' UNION ALL
                SELECT '515' UNION ALL
                SELECT '516' UNION ALL
                SELECT '517' UNION ALL
                SELECT '518' UNION ALL
                SELECT '519' UNION ALL
                SELECT '520' UNION ALL
                SELECT '530' UNION ALL
                SELECT '540' UNION ALL
                SELECT '541' UNION ALL
                SELECT '546' UNION ALL
                SELECT '551' UNION ALL
                SELECT '555' UNION ALL
                SELECT '557' UNION ALL
                SELECT '559' UNION ALL
                SELECT '561' UNION ALL
                SELECT '562' UNION ALL
                SELECT '563' UNION ALL
                SELECT '564' UNION ALL
                SELECT '567' UNION ALL
                SELECT '570' UNION ALL
                SELECT '571' UNION ALL
                SELECT '573' UNION ALL
                SELECT '574' UNION ALL
                SELECT '580' UNION ALL
                SELECT '585' UNION ALL
                SELECT '586' UNION ALL
                SELECT '590' UNION ALL
                SELECT '600' UNION ALL
                SELECT '601' UNION ALL
                SELECT '602' UNION ALL
                SELECT '603' UNION ALL
                SELECT '604' UNION ALL
                SELECT '605' UNION ALL
                SELECT '606' UNION ALL
                SELECT '607' UNION ALL
                SELECT '608' UNION ALL
                SELECT '609' UNION ALL
                SELECT '610' UNION ALL
                SELECT '611' UNION ALL
                SELECT '612' UNION ALL
                SELECT '613' UNION ALL
                SELECT '614' UNION ALL
                SELECT '615' UNION ALL
                SELECT '616' UNION ALL
                SELECT '617' UNION ALL
                SELECT '618' UNION ALL
                SELECT '619' UNION ALL
                SELECT '620' UNION ALL
                SELECT '623' UNION ALL
                SELECT '626' UNION ALL
                SELECT '627' UNION ALL
                SELECT '628' UNION ALL
                SELECT '630' UNION ALL
                SELECT '631' UNION ALL
                SELECT '636' UNION ALL
                SELECT '641' UNION ALL
                SELECT '646' UNION ALL
                SELECT '647' UNION ALL
                SELECT '649' UNION ALL
                SELECT '650' UNION ALL
                SELECT '651' UNION ALL
                SELECT '657' UNION ALL
                SELECT '660' UNION ALL
                SELECT '661' UNION ALL
                SELECT '662' UNION ALL
                SELECT '664' UNION ALL
                SELECT '669' UNION ALL
                SELECT '670' UNION ALL
                SELECT '671' UNION ALL
                SELECT '678' UNION ALL
                SELECT '679' UNION ALL
                SELECT '682' UNION ALL
                SELECT '684' UNION ALL
                SELECT '689' UNION ALL
                SELECT '700' UNION ALL
                SELECT '701' UNION ALL
                SELECT '702' UNION ALL
                SELECT '703' UNION ALL
                SELECT '704' UNION ALL
                SELECT '705' UNION ALL
                SELECT '706' UNION ALL
                SELECT '707' UNION ALL
                SELECT '708' UNION ALL
                SELECT '709' UNION ALL
                SELECT '710' UNION ALL
                SELECT '711' UNION ALL
                SELECT '712' UNION ALL
                SELECT '713' UNION ALL
                SELECT '714' UNION ALL
                SELECT '715' UNION ALL
                SELECT '716' UNION ALL
                SELECT '717' UNION ALL
                SELECT '718' UNION ALL
                SELECT '719' UNION ALL
                SELECT '720' UNION ALL
                SELECT '724' UNION ALL
                SELECT '727' UNION ALL
                SELECT '731' UNION ALL
                SELECT '732' UNION ALL
                SELECT '734' UNION ALL
                SELECT '737' UNION ALL
                SELECT '740' UNION ALL
                SELECT '747' UNION ALL
                SELECT '752' UNION ALL
                SELECT '754' UNION ALL
                SELECT '757' UNION ALL
                SELECT '758' UNION ALL
                SELECT '760' UNION ALL
                SELECT '763' UNION ALL
                SELECT '764' UNION ALL
                SELECT '765' UNION ALL
                SELECT '767' UNION ALL
                SELECT '770' UNION ALL
                SELECT '772' UNION ALL
                SELECT '773' UNION ALL
                SELECT '774' UNION ALL
                SELECT '775' UNION ALL
                SELECT '778' UNION ALL
                SELECT '780' UNION ALL
                SELECT '781' UNION ALL
                SELECT '784' UNION ALL
                SELECT '785' UNION ALL
                SELECT '786' UNION ALL
                SELECT '787' UNION ALL
                SELECT '800' UNION ALL
                SELECT '801' UNION ALL
                SELECT '802' UNION ALL
                SELECT '803' UNION ALL
                SELECT '804' UNION ALL
                SELECT '805' UNION ALL
                SELECT '806' UNION ALL
                SELECT '807' UNION ALL
                SELECT '808' UNION ALL
                SELECT '809' UNION ALL
                SELECT '810' UNION ALL
                SELECT '811' UNION ALL
                SELECT '812' UNION ALL
                SELECT '813' UNION ALL
                SELECT '814' UNION ALL
                SELECT '815' UNION ALL
                SELECT '816' UNION ALL
                SELECT '817' UNION ALL
                SELECT '818' UNION ALL
                SELECT '819' UNION ALL
                SELECT '822' UNION ALL
                SELECT '828' UNION ALL
                SELECT '830' UNION ALL
                SELECT '831' UNION ALL
                SELECT '832' UNION ALL
                SELECT '833' UNION ALL
                SELECT '835' UNION ALL
                SELECT '836' UNION ALL
                SELECT '843' UNION ALL
                SELECT '844' UNION ALL
                SELECT '845' UNION ALL
                SELECT '847' UNION ALL
                SELECT '848' UNION ALL
                SELECT '850' UNION ALL
                SELECT '855' UNION ALL
                SELECT '856' UNION ALL
                SELECT '857' UNION ALL
                SELECT '858' UNION ALL
                SELECT '859' UNION ALL
                SELECT '860' UNION ALL
                SELECT '861' UNION ALL
                SELECT '862' UNION ALL
                SELECT '863' UNION ALL
                SELECT '864' UNION ALL
                SELECT '865' UNION ALL
                SELECT '866' UNION ALL
                SELECT '867' UNION ALL
                SELECT '868' UNION ALL
                SELECT '869' UNION ALL
                SELECT '870' UNION ALL
                SELECT '872' UNION ALL
                SELECT '876' UNION ALL
                SELECT '877' UNION ALL
                SELECT '878' UNION ALL
                SELECT '880' UNION ALL
                SELECT '881' UNION ALL
                SELECT '882' UNION ALL
                SELECT '888' UNION ALL
                SELECT '900' UNION ALL
                SELECT '901' UNION ALL
                SELECT '902' UNION ALL
                SELECT '903' UNION ALL
                SELECT '904' UNION ALL
                SELECT '905' UNION ALL
                SELECT '906' UNION ALL
                SELECT '907' UNION ALL
                SELECT '908' UNION ALL
                SELECT '909' UNION ALL
                SELECT '910' UNION ALL
                SELECT '911' UNION ALL
                SELECT '912' UNION ALL
                SELECT '913' UNION ALL
                SELECT '914' UNION ALL
                SELECT '915' UNION ALL
                SELECT '916' UNION ALL
                SELECT '917' UNION ALL
                SELECT '918' UNION ALL
                SELECT '919' UNION ALL
                SELECT '920' UNION ALL
                SELECT '925' UNION ALL
                SELECT '928' UNION ALL
                SELECT '931' UNION ALL
                SELECT '935' UNION ALL
                SELECT '936' UNION ALL
                SELECT '937' UNION ALL
                SELECT '939' UNION ALL
                SELECT '940' UNION ALL
                SELECT '941' UNION ALL
                SELECT '947' UNION ALL
                SELECT '949' UNION ALL
                SELECT '951' UNION ALL
                SELECT '952' UNION ALL
                SELECT '954' UNION ALL
                SELECT '956' UNION ALL
                SELECT '957' UNION ALL
                SELECT '959' UNION ALL
                SELECT '969' UNION ALL
                SELECT '970' UNION ALL
                SELECT '971' UNION ALL
                SELECT '972' UNION ALL
                SELECT '973' UNION ALL
                SELECT '975' UNION ALL
                SELECT '976' UNION ALL
                SELECT '978' UNION ALL
                SELECT '979' UNION ALL
                SELECT '980' UNION ALL
                SELECT '984' UNION ALL
                SELECT '985' UNION ALL
                SELECT '989' UNION ALL
                SELECT '999'
            ) np
            ORDER BY RAND()
            LIMIT 1
    )
)
